### ISSUE TITLE
can not retweet

### ISSUE THREAD

**Issue by Tetoku** [dimdenGD/OldTweetDeck#100]
When I try to retweet, I get an error and cannot do it.
Error message
Failed: Retweet - An unknown error occurred. Please try again shortly.

**Comment by upiwart21** [comment]
same bro

**Comment by akicd** [comment]
Known issues:
Retweeting doesn't work
Deleting doesn't work
Replies don't show properly

Let's just sit tight and hope they fix the problem.

**Comment by upiwart21** [comment]
maybe twitter is down
