### ISSUE TITLE
Update notification a bit too agressive.

### ISSUE THREAD

**Issue by Dajova** [dimdenGD/OldTweetDeck#105]
I know that you want to notify the users about the new updates, but it hits a bit too frequently, to the point of being kinda annoying.
Even if you update to the latest version, it still pops up.

**Comment by dimdenGD** [comment]
It doesn't show anything when you update to last version though

**Comment by Dajova** [comment]
It does. I have the latest version and it still pops up.

**Comment by dimdenGD** [comment]
What message do you get? Are you sure you're on 3.1.4?

**Comment by Dajova** [comment]
Hmm, i updated the file manually, but it seems that Firefox still thinks its on 3.0.2. I know i replaced the file with the 3.1.4 update... Im guessing it needs to be reinstalled for it to take effect, cus it does work fine except the constant message.

**Comment by dimdenGD** [comment]
Try pressing "Reload" button on extension

**Comment by Dajova** [comment]
I dont have a reload button on it, only a on/off toggle. anyway, ill reinstall it.
