### ISSUE TITLE
Tweet replies not clickable

### ISSUE THREAD

**Issue by membrant** [dimdenGD/OldTweetDeck#107]
A tweet's replies can't be clicked on tweetdeck, one has to open the actual Tweet via Twitter and see the replies. 

Also, is there a release for Edge browser? I just see Chrome and Firefox.

**Comment by archeruwu** [comment]
Edge is chrome, just [load the unpacked zip into edge](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading)

Also replies should be fixed on the [latest release](https://github.com/dimdenGD/OldTweetDeck/releases/tag/v3.1.4)

**Comment by membrant** [comment]
Thank you
