### ISSUE TITLE
Infinite loading circle

### ISSUE THREAD

**Issue by SilentPrayeCG** [dimdenGD/OldTweetDeck#110]
Today page wont load anymore. Infinite rotating loading circle in middle of screen. Bunch of errors in F12 console.
FF Nightly. Tried localStorage.OTDalwaysUseLocalFiles = '1' and reinstall. Tho didn't tried to clear cookies.

**Comment by dimdenGD** [comment]
Can't reproduce, loads fine for me on Firefox and Chromium

**Comment by SilentPrayeCG** [comment]
> Can't reproduce, loads fine for me on Firefox and Chromium

Ok it was something on my side. Cleared cookies and relogined. It's ok now. Thanks.
