### ISSUE TITLE
Search columns not populating for hours after OldTweetDeck is started

### ISSUE THREAD

**Issue by snowbound** [dimdenGD/OldTweetDeck#112]
This may be rate limiting in action. I shut down my Windows 10 computer at night. 8 to 9 hours later I turn it on along OldTweetdeck. I have two search columns one for my own tweets and one for another Twitter user. Neither of these columns will populate for 4+ hours it just shows loading and a spinning circle. Is this due to rate limiting? All of the other columns populate fine.

**Comment by RH-2010** [comment]
Same here, but how can you tell it's rate limit? Like to know.

**Comment by Rooooooobert** [comment]
According to Dimden's explanation, the search- and usercolumns are subject to rate limits. You will need patience, ;-)

**Comment by snowbound** [comment]
I have stopped going to people's profiles or looking at their other tweets. So far it has been 13 hrs since I had shut down OldTweetdeck and 8 hours since started it back up without these columns.

**Comment by RH-2010** [comment]
Yes I also noticed, after refresh all columns stay empty. Have to wait unfortunately.

**Comment by snowbound** [comment]
After being started 6 hrs ago OldTweetDeck finally populated these two
columns. So these columns took 14 hrs to show up. That included 8 hours
while the computer was powered down plus 6 additional hours after the
computer was powered back up.

**Comment by JustinRedmond4284** [comment]
Only my Home and Messages columns show up for me while other columns of users I follow are doing the same 'loading circle'.  Even worse, I found out that I'm unable to load pretty much anything from Twitter. From user profiles to single posts, nothing is loading.

Here's what I see at someone's profile:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/136798411/167b2a7c-970c-4cfd-8b85-0378b8aae03d)
Here's what I see without OldTwitter:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/136798411/f07089fa-f9bf-4c53-bc98-5b951b8a38e6)

Guess Twitter never got rid of the "Rate limit exceeded' feature. I installed OldTweetDeck on the 15th, so I guess I read too many Tweets in that time. I'm uninstalling OldTweetDeck for now and hope that Twitter returns to a useable state.

**Comment by snowbound** [comment]
I think if one ventures off and reads a thread from a single post on Twitter or goes to someone's profile and looks through their Tweets then I guess the rate limit is triggered. I have two Twitter accounts and only use one of the accounts regularly. I have 7 columns in OldTweetdeck for messages and posts from these two accounts plus 2 search columns.  This is the first day in probably 4 or 5 days that OldTweetdeck fully populated all of the 7 columns. The web browser had been closed for 10 hours over night.

**Comment by knowthisnumber** [comment]
I'm also having issues with the search columns and I don't think it's the rate limit. I can use one column for a certain search with no problem but another column (usually when I search a name) won't load at all. I can look through Twitter with no problem so again, I don't think it's the rate limit. I also use Chrome/web browser.

**Comment by JustinRedmond4284** [comment]
I'm able to use Twitter normally now. I'm not sure the exact time (as I was asleep), but I know about three hours ago I still was rate limited. I want to say there's a set-time for the rate limit to pass, maybe 12 hours at the least.

**Comment by RH-2010** [comment]
I am pretty much done with this X medium, getting worse by the day.

**Comment by snowbound** [comment]
Today when I opened OldTweetDeck 3 columns are now showing 

"No recent Tweets.
New Tweets will appear here."

Two of the 3 columns are search columns one for my own Tweets and someone else. The third column is for a 2nd account I have. I just checked now and all but the 2nd search column has populated

I am not rate limited as Twitter.com is show Tweets under my Followed column.

**Comment by psylenced** [comment]
> According to Dimden's explanation, the search- and usercolumns are subject to rate limits. You will need patience, ;-)

To bypass the user column limit, I created a 1 person private list and switched to that.

That seemed to work, although I switched it a month or two ago and is still working. Haven't changed back to single user follows - so may or may not have changed.
