### ISSUE TITLE
URL is now being counted toward total tweet char count 

### ISSUE THREAD

**Issue by Neobond** [dimdenGD/OldTweetDeck#113]
Seems like the URL is now being counted fully towards the tweet char count..

This when automated goes through fine:  With today's highlighted deal, discover the perfect platform to search for jobs that fit your schedule! Browse and apply to thousands of remote work from home jobs and save more than half the cost! #FlexJobs #Deals #Jobs https://www.neowin.net/deals/save-57-off-a-1-yr-subscription-to-flexjobs-now-just-2999/

![SNAG-0000](https://github.com/dimdenGD/OldTweetDeck/assets/42996358/8028b059-0d80-4fed-a324-4a0e6fc1f0b6)

But when I enter the same thing in OldTweetDeck

![SNAG-0001](https://github.com/dimdenGD/OldTweetDeck/assets/42996358/e8f9b4df-80fc-426a-a534-93584ad2f53e)

**Comment by dimdenGD** [comment]
Fixed
