### ISSUE TITLE
Full Tweet text not appearing in Tweetdeck

### ISSUE THREAD

**Issue by Stochos** [dimdenGD/OldTweetDeck#114]
**From OldTweetDeck**

<img width="256" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/15600804-dd8b-4a78-ab6b-560e4d0d2763">

**From Twitter.com**
https://twitter.com/Schuldensuehner/status/1703817367061508292

<img width="591" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/56102667-2c50-4b2f-b0a9-273cb13120cf">

Another example:
https://twitter.com/Gerashchenko_en/status/1703804328358584690

<img width="259" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/172d364a-92ac-45d0-8c50-4e1f27c37af7">

<img width="599" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/5f2ce160-1456-4f98-908a-b352933c12ad">

**Comment by Stochos** [comment]
> There's no real fixing this because it's about what API is being used. The old API, which is better for us because it essentially ignores the rate limit, doesn't send all of the tweet. If you want all of the tweet on timeline itself, you have to put up with the new API.
> 
> However, something did change over the last few updates either on OTD's side or X's, where previously a long-form tweet would display a "show more" on the timeline and now it just awkwardly ends. If this was on Den's side, and it was a choice, I'd love to have the "show more" come back so I know I'm missing something instead of having to guess by the lack of a period. If one of the Japanese accounts I follow does it it's much harder to tell, now. Was thinking of making a request post on this to see which it is and if it can be returned.
> 
> Still, choice or not, this is better (for most non-premium users and even a few who are) than having to use the new API, which is likely an eventually given their stated goals to axe the old ones.

Agree. I missed that "Show more" wasn't appearing anymore.

**Comment by dimdenGD** [comment]
After changing API key, internal API stopped returning "Show more" for some reason. I've added "Expand tweet" button that will fetch full text and add it to tweet

**Comment by Stochos** [comment]
Long tweets which are quoted don't appear in full. 
https://twitter.com/KanwalSibal/status/1704198162448056580
<img width="251" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/736f16eb-2214-4ddd-a4e4-d01231139522"> <img width="261" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/410a3385-0597-471a-8d0e-33df9904e542">
<img width="363" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/cbfc8797-9d3d-4dd1-81f0-8dac23f7415d">


**_Minor issue:_**
When "Expand Tweet" is clicked if just reveal text of url and not in hypertext format, the text of the tweet is not fully revealed. 

<img width="261" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/376fdc8e-31c2-4a4a-bb54-496f254709e0"> <img width="255" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/c51ab33d-1ca9-4582-a7f7-6ec8218a7ad1">
Tweet as per Twitter.com:
https://twitter.com/RobinBrooksIIF/status/1704592204251930846

**Comment by Stochos** [comment]
Retweets of longform tweets don't show the "Expand tweet" link.

**Comment by Stochos** [comment]
Appreciate your efforts but the issue still appears. 
**_From OldTweetDeck_**
<img width="229" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/5f5a4523-2861-4d3b-bf01-0c360e91deb6"> <img width="245" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/70655602-c65e-4f42-a561-f9a35aa85a4f">
**_Twitter.com_**
https://twitter.com/Eskom_SA/status/1704931132297326657
<img width="361" alt="image" src="https://github.com/dimdenGD/OldTweetDeck/assets/27431568/430900e0-9f43-43c5-b1ea-8cedf8a507ea">

Perhaps the black spaces or paragraph spaces are causing this?
