### ISSUE TITLE
Emoji Display Error

### ISSUE THREAD

**Issue by MarbleJams** [dimdenGD/OldTweetDeck#115]
Hello, I loaded up my old Tweetdeck today. Everything else is working perfectly fine, but it seems that emojis their next peoples usernames are now going on a line underneath instead of being displayed next to them like usual. 

This isn’t a major issue so you don’t have to work on it immediately

![IMG_1813](https://github.com/dimdenGD/OldTweetDeck/assets/145527270/059cccce-b628-482e-aaf3-ec181fed2959)

**Comment by dimdenGD** [comment]
Can't reproduce, emojis work fine for me
