### ISSUE TITLE
Replies are not showing anymore

### ISSUE THREAD

**Issue by thiagoradice** [dimdenGD/OldTweetDeck#117]
After upgrading to 3.1.5, the replies are not showing at all

![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/a102fb60-89d5-472d-95a7-94ba4326ae5a)

And sometimes this thing happens

![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/8bedebba-34e1-45d4-bf9e-5a4b147cdf4c)

**Comment by dimdenGD** [comment]
Browser?

**Comment by dimdenGD** [comment]
I can't reproduce it, what errors in console do you get when it happens? F12 > Console

**Comment by thiagoradice** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/62ff67c4-e9b2-48fb-b970-597fa8fe1492)

**Comment by dimdenGD** [comment]
scroll down

**Comment by thiagoradice** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/67cdcdb5-0697-4e62-bc04-2ec847f57d2d)

That's all

**Comment by dimdenGD** [comment]
Try opening tweet replies with console open and see if theres new errors happening when you do it

**Comment by thiagoradice** [comment]
It took a couple of seconds to show up

![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/244e165e-ba77-49b4-9f10-168368131b17)

**Comment by dimdenGD** [comment]
Unfortunately I don't really see anything useful

**Comment by archeruwu** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/18449883/a6987e9c-5f04-46c9-ad01-45d99e1c9729)
Idk if this is useful, but this is what I get whenever anything happens on otd, replies are the same deal, Edge and Firefox

**Comment by thiagoradice** [comment]
I've already restarted the browser, and cleaned the caches. What is odd is that I tried even rollback to tha previous version (3.1.4) and the problem persisted.

**Comment by thiagoradice** [comment]
maybe there's something in my network preventing the connections?

**Comment by dimdenGD** [comment]
go to Network tab and paste `timeline/conversation` into filter and check if requests are going fine

**Comment by thiagoradice** [comment]
I don't know if it helps
![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/7f1c576c-08b6-4ca4-89f6-32107f06489b)

**Comment by dimdenGD** [comment]
you didnt paste the filter so all of these are unrelated

**Comment by thiagoradice** [comment]
nothing returned
![image](https://github.com/dimdenGD/OldTweetDeck/assets/613655/e52cddcb-8642-43a3-a167-50cf71af07a0)

**Comment by dimdenGD** [comment]
I just updated something and updated files in release (without bumping version), can you download new zip file and reinstall it and see if it fixes the issue?

**Comment by thiagoradice** [comment]
Sure. Just a second.

**Comment by thiagoradice** [comment]
Cool! Now it's working! Thanks a lot!
