### ISSUE TITLE
Expanding Retweeted Tweet

### ISSUE THREAD

**Issue by ItIsSeven** [dimdenGD/OldTweetDeck#118]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/63268023/5d09902c-61d5-42d4-be9a-452132d07c7e)
Tweet: https://twitter.com/Amena__Bakr/status/1704728102427869296

Expanding a retweeted tweet not working as intended, works fine when expanding the original though.

**Comment by archeruwu** [comment]
Try updating to the latest release.

**Comment by ItIsSeven** [comment]
> Try updating to the latest release.

Am on 3.1.6 already
