### ISSUE TITLE
Bookmark support?

### ISSUE THREAD

**Issue by sockfox** [dimdenGD/OldTweetDeck#119]
Hi! This is my first proper github issue, and I apologize if it's an inconvenience at all, but my only complaint about the old tweetdeck interface is that I'm unable to add things to bookmarks. I use an automated script to download my bookmarks automatically, and was wondering if it's possible at all to add a button (even if it's in a context menu) to add a specific tweet to my bookmarks.

**Comment by dimdenGD** [comment]
Added
