### ISSUE TITLE
[Request] Compatablity with Twitter 原寸びゅー

### ISSUE THREAD

**Issue by suzumiyabi** [dimdenGD/OldTweetDeck#12]
https://chrome.google.com/webstore/detail/twitter-view-original-ima/bkpaljhmpehdbjkoahohlhkhlleaicel

**Comment by dimdenGD** [comment]
Out of scope for this project, ask that extension developer to update it.

**Comment by wave-dash** [comment]
As of about a week ago, twOpenOriginalImage is abandoned. Github privated, Chrome extension taken down, even removed from Greasy Fork.

I understand that it's a lot of work to basically adopt an extension, but considering BetterTweetDeck was rescued, I don't think it's unreasonable to request that another Tweetdeck extension be saved as well.
