### ISSUE TITLE
Rate limit bypass

### ISSUE THREAD

**Issue by RH-2010** [dimdenGD/OldTweetDeck#123]
Turning on Rate limit bypass gave me rate limit instantly 🧐😂

**Comment by ogbrana** [comment]
hey, don't turn on bypass before your rate limit expires. other columns don't loading, but i don't know why :(

**Comment by knowthisnumber** [comment]
Same here. Search columns aren't loading for me.

**Comment by RH-2010** [comment]
You are right ogbrana, works

**Comment by RH-2010** [comment]
Not for long :(

**Comment by TheAGames10** [comment]
I'm rate-limited, and the option does not work no matter if it's on or off, nothing changes meaning the columns won't load in anymore.

**Comment by TheAGames10** [comment]
I'm rate-limited, and I cannot get the bypass to work no matter if it's on or off, nothing changes meaning the columns won't load in anymore. @dimdenGD
