### ISSUE TITLE
User column

### ISSUE THREAD

**Issue by gvladas** [dimdenGD/OldTweetDeck#127]
The User column (for my account) is not loading. Loading... lasts indefinitely

![Image_001](https://github.com/dimdenGD/OldTweetDeck/assets/85923127/71404db8-19fa-4240-a514-84568f5ba8c5)

**Comment by TheAGames10** [comment]
I have the setting for bypassing rate limit, and it works, but then after a while, it makes the user column load a bit before saying there are no recent tweets.

**Comment by perigozin** [comment]
Bypass rate limit isn't working anymore

**Comment by gvladas** [comment]
> User and Search uses the new API, which is subject to the rate limit. At best you can try the new rate limit button in the options, check the release notes to read about it.

The "Enable rate limit bypass" option does not help. Still can't add a column for my own account. On the other hand, I can easily add columns for other people's accounts.

**Comment by missateneis** [comment]
T

> User and Search uses the new API, which is subject to the rate limit. At best you can try the new rate limit button in the options, check the release notes to read about it.

I have an issue when user column stops loading after several scrolls. Happens with all user columns.  Loading completely fine on the website, doesnt look like a limit issue.

**Comment by TheAGames10** [comment]
Yea, I cannot get Tweetdeck columns to load anymore, and the option to turn on and off the rate limit bypass doesn't work anymore, it stays the same no matter what.

**Comment by TheAGames10** [comment]
@dimdenGD Tonight, my own User column stopped working after turning the rate limit bypass option on. I tried refreshing TweetDeck, deleting the column and then putting a new user column for me, but nothing seems to fix it.


![Capture](https://github.com/dimdenGD/OldTweetDeck/assets/111199398/03995ed0-e385-4dfb-b87b-e88958c12444)
