### ISSUE TITLE
No longer working. Asks to buy X Premium

### ISSUE THREAD

**Issue by membrant** [dimdenGD/OldTweetDeck#128]
Tweetdeck is no longer visible, it routes immediately to https://twitter.com/i/premium_sign_up

**Comment by AdamMReese** [comment]
Are you using the newest version and going to https://twitter.com/i/tweetdeck ?

**Comment by membrant** [comment]
> Are you using the newest version and going to https://twitter.com/i/tweetdeck ?

if you click on the link you posted, it shows "Hmm...this page doesn’t exist. Try searching for something else."

**Comment by dimdenGD** [comment]
That means you didn't install the extension

**Comment by membrant** [comment]
> That means you didn't install the extension

Hmm, I just extracted the Chrome extension for Edge. i'll try again and update

**Comment by membrant** [comment]
I figured out. Edge browser update turned Developer as Off, so the extension was not active. I turned it back on and it works! Thank you
