### ISSUE TITLE
Firefox - addon not verified

### ISSUE THREAD

**Issue by yodos1** [dimdenGD/OldTweetDeck#135]
Trying to add the latest OldTweetDeck to firefox.  It keeps saying its not verified and will not install it even after I change that xpinstall.signatures.required setting to "false".  Is there a work-around im not seeing?.

**Comment by dimdenGD** [comment]
are you using Firefox Developers or Beta

**Comment by yodos1** [comment]
Version 118.0.2 .. dont think its beta or developers...

**Comment by dimdenGD** [comment]
You have to use Firefox Developers or Beta for this to work as said in README
