### ISSUE TITLE
+User

### ISSUE THREAD

**Issue by hillmanglover** [dimdenGD/OldTweetDeck#137]
Unable to add a user from the + menu.  It goes through the process but dosen't find the name searched.

**Comment by hillmanglover** [comment]
Thanks for getting in touch,

Won’t add any @name I add.

**Comment by TheAGames10** [comment]
I have also been having an issue, my user column will not load at all, and I can't refresh to fix it, can't re-add the column, and the Rate Limit Bypass doesn't fix the user column but it's working for the other columns.

**Comment by Ryotaiku** [comment]
Getting the same issue. I'll get a prompt to log in with my second account, but it doesn't show up after the process is done.

**Comment by dimdenGD** [comment]
You can put `!` before username (without @ ) to do exact username search.
