### ISSUE TITLE
OldTD 2.0.1 breaks the BetterTD fork. 

### ISSUE THREAD

**Issue by GoldenLumia** [dimdenGD/OldTweetDeck#14]
Hey, thanks for all your hard work. Seems that the changes you made in the latest versions have broken your BetterTD fork, it does not seem to load itself properly. Your BetterTD repo doesn't seem to have issues enabled, so I'm just letting you know here.

Browser: Vivaldi 6.1.3035.302 (Stable channel) (32-bit) 

Rolled back to your initial release and everything works perfectly. Thank you!

**Comment by PRGilland** [comment]
Getting the same issues, also on Vivaldi. Was working fine over an hour ago until I moved the unpacked files into another folder and closed the browser. Attached are the errors it was giving me.
![vivaldi_2023-08-19_21-02-58](https://github.com/dimdenGD/OldTweetDeck/assets/53190048/9dc6de82-331f-4c2c-8ee8-2db2bbb96781)

![vivaldi_2023-08-19_21-03-09](https://github.com/dimdenGD/OldTweetDeck/assets/53190048/0c879490-ff6e-4e74-ad75-9518a4c18287)

**Comment by dimdenGD** [comment]
I've made an update to BTD fork, it seems to make it work better. Still need to refresh sometimes but much less than before, at least for me.
When refreshing with cache clear (CTRL+SHIFT+R) it seems to never work, but on regular (F5) refreshes it works most of the time

**Comment by GoldenLumia** [comment]
> I've made an update to BTD fork, it seems to make it work better. Still need to refresh sometimes but much less than before, at least for me. When refreshing with cache clear (CTRL+SHIFT+R) it seems to never work, but on regular (F5) refreshes it works most of the time

Yeah, already noticing a solid improvement. I figured document_end was the problem, but I didn't want to be nosy. Just edited the manifest.json to match your commit, and it's working pretty much perfectly now. Might want to post a new release for less tech inclined people. I see you have issues enabled on BetterTD now, so I will close this issue. Thank you so much again for keeping my preferred way of using Twitter up a bit longer.
