### ISSUE TITLE
The ellipsis symbol (…) is not being displayed.

### ISSUE THREAD

**Issue by Uron0238** [dimdenGD/OldTweetDeck#15]
Some of the ellipses within the tweet are not being displayed.
Upon testing, it appears that ellipses at the beginning or end of a tweet are being omitted.
ex) …test……test…… -> test……test

**Comment by unirun** [comment]
Hello,

I just wanted to chime in and mention that I've also encountered this issue on OldTweetDeck. Specifically, when displaying tweets with the "…" character at the beginning and end, they seem to be trimmed.

Example: `……Something……`
Becomes: `Something`

I thought it was important to share that others are also experiencing this. Hope a resolution can be found soon. Thank you for all your hard work on this project!
