### ISSUE TITLE
Officially dead/unworking?

### ISSUE THREAD

**Issue by CherryGryffon** [dimdenGD/OldTweetDeck#157]
For at least a few days now, the link to tweetdeck (-com/i/tweetdeck) is no longer working. Is this permanent? Is there another workaround I should be looking for that I don't see? 

Just curious so I can remove the add-on if it's gone for good, or do what needs to be done to fix it! :)

**Comment by dimdenGD** [comment]
it works, im using it rn

**Comment by CherryGryffon** [comment]
Will do that, thank you!!
