### ISSUE TITLE
Column API is no longer available.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTweetDeck#159]
On January 19, 2024 at 11:58 am,
 OldTweetDeck suddenly broke the domain of the API for all columns and all columns are no longer displayed.
 Tweets can be used as normal.

 Please fix this somehow...! 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/139020260/784dfbcb-e092-4627-b207-3da2d9a6b369)

**Comment by boilinabag** [comment]
same here in USA. stopped working. reloaded the extension, same result. damn.

**Comment by NotZoeyDev** [comment]
Looks like they killled one of the endpoints that old tweetdeck uses to get its configuration, I think this is going to be fully dead unless there's a way to replicate that endpoint.

**Comment by bootjp** [comment]
Looks like it's under investigation.

> Let's just wait and see if twitter servers are just maybe having an issue, like last time. then I'll try to fix OldTweetDeck

https://twitter.com/d1mden/status/1748182065663680597

**Comment by boilinabag** [comment]
same here in los angeles. i thought it might be their server, but it looks
different this time.

**Comment by EZ2Alpa** [comment]
I hear it is coming back!
[https://twitter.com/d1mden/status/1718359080668950682](url)

**Comment by Stochos** [comment]
Partially back. 

### **Appreciate the work of @dimdenGD**
 
Some stuff not displaying and could be broken
- Threads indicator not being displayed
- "Expand threads" gives error when clicked
- History of tweets from individual accounts are not being displayed in a column

And Guru Dimden already indicated that notifications are not working and is harder to get back.

**Comment by ne0c0de** [comment]
I were disabled auto updates from server so I have still problm. @dimdenGD can you please tell us which files should be updated?

**Comment by ne0c0de** [comment]
I just copied changes from interception.js an tweets part started to working flawlessly. thanks.

**Comment by dimdenGD** [comment]
New version published on releases page

**Comment by keremcankabadayi** [comment]
I'm uncertain if the issue is related to this, but there seems to be a problem loading any user column

![image](https://github.com/dimdenGD/OldTweetDeck/assets/23381187/e9984a08-625c-4cd2-8fa9-440c2301e8f7)

**Comment by dimdenGD** [comment]
try turning off or on rate limit bypass option

**Comment by keremcankabadayi** [comment]
> try turning off or on rate limit bypass option

nope, didnt work.
version: 3.2.0
1. turn off 
2. refresh page
3. turn on
still stuck while loading. columns, collections working fine btw

**Comment by dimdenGD** [comment]
maybe you got rate limited completely, it works for me

**Comment by keremcankabadayi** [comment]
i also use `OldTwitter`, i can see any user on `twitter.com`

![image](https://github.com/dimdenGD/OldTweetDeck/assets/23381187/910d6e95-fc93-4652-90e9-1a9f457b2ae3)

**Comment by sravanpannala** [comment]
Are collections gone forever?
![image](https://github.com/dimdenGD/OldTweetDeck/assets/57152030/b9dd8694-2b88-44af-a0e2-704adf872b44)

**Comment by dimdenGD** [comment]
fixed collections

**Comment by ne0c0de** [comment]
configuration.json is getting 410 gone response again...
