### ISSUE TITLE
Clicks not registering in Chrome

### ISSUE THREAD

**Issue by SubSub52** [dimdenGD/OldTweetDeck#16]
Clicking anywhere asides the column on the far left, the column that you can collapse/expand, doesn't work in Chrome. No clicks register, the columns don't acknowledge the existence of the mouse cursor.

The fix in the case was opening 'Extensions' - Old Tweetdeck Details - Site Settings - Change the 'Insecure Content' dropdown menu to 'Allow'.

Tried with and without BTD, but issue remains.
Latest Chrome Version: 116.0.5845.97

Update: Issue has returned after a few page refreshes. Insecure content remains 'allowed'.

**Comment by ubertrance** [comment]
Seconding this issue. When I first installed the extension, it worked fine (tho I had one quirk where if I clicked on an image, it would simply zoom out to the point where it wasn't viewable). Once I closed my browser and opened it back up, the no click register issue happened. 

 I downgraded to the old build avalible and it works just fine now.

**Comment by dimdenGD** [comment]
I updated something, can you see if it works now

**Comment by SubSub52** [comment]
Yes, issue appears resolved. Shall return and update if required. Thanks..
