### ISSUE TITLE
change check interval

### ISSUE THREAD

**Issue by ne0c0de** [dimdenGD/OldTweetDeck#161]
Hi, is there a way to change check interval for new tweets? I guess it's 3 seconds right now and I want to change it to a second for some period of times. is this possible?

**Comment by dimdenGD** [comment]
This is not possible.

**Comment by ne0c0de** [comment]
doesn't possible even change a variable value on the code?

**Comment by dimdenGD** [comment]
It's very hard to change code of tweetdeck itself because its minified, tweetdeck uses some specific scheduling mechanism based on rate limit, it would took too much effort to try to understand how it works and to somehow accelerate it

**Comment by ne0c0de** [comment]
I already injected many lines of code to current scripts to took out tweets from tweetdeck to my websocket so it's not too much hard for me to change the code but I wonder if it's easy or hard and now I understand that it's not that much easy to make this change :)
