### ISSUE TITLE
Likes Button is not working.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTweetDeck#165]
After the API was restored, there's a glitch where you can likes button something multiple times and it's not treated as a like.
(When looking at the UI, the like count is not increasing, and when looking at the detailed tweet, you can confirm that the like icon is before the like).

**Comment by VelvetShadows** [comment]
Nothing displays in the likes column either.
Started earlier today, as both adding likes and displaying them definitely worked this morning.

**Comment by knowthisnumber** [comment]
> Nothing displays in the likes column either. Started earlier today, as both adding likes and displaying them definitely worked this morning.

Having that same issue.

**Comment by dimdenGD** [comment]
Fixed
