### ISSUE TITLE
Unable to Expand Tweet

### ISSUE THREAD

**Issue by Monstar316** [dimdenGD/OldTweetDeck#168]
Hi,

I am unable to expand any tweet within OTD. It's just shows 'error' whenever I click on the 'expand' option within the tweet.

![image](https://github.com/dimdenGD/OldTweetDeck/assets/16082971/886c2bdb-f1e9-48f8-8ca4-0bfd1783c774)

I don't know if the above errors have anything to do with it.

**Comment by dimdenGD** [comment]
you're rate limited

**Comment by Monstar316** [comment]
But I can expand the tweets within the X app!

**Comment by dimdenGD** [comment]
these are separate
