### ISSUE TITLE
images gradually shrinks

### ISSUE THREAD

**Issue by traplover4200** [dimdenGD/OldTweetDeck#17]
[video of my problem nsfw](https://twitter.com/twinklover4200/status/1693271969754431960)

**Comment by ItsChicobo** [comment]
I am indeed having this problem. It's weird - the image just...shrinks away whenever I click on one from the timeline

**Comment by kakakaya** [comment]
Issue title should be renamed as we can't  recognize the problem until watch the video. I suggest some titles:

- `Picture displayed on modal window gradually shrinks step by step, if window size is not enough`

**Comment by atakamizawa** [comment]
The issue improved once I cleared the cache that I originally had.

**Comment by dlinv773** [comment]
this is still happening for me with latest version.

**Comment by dimdenGD** [comment]
Does this still happen?

**Comment by dlinv773** [comment]
The issue is fixed. Thank you.


David Linville
***@***.***
