### ISSUE TITLE
Replies to accounts I don't follow from accounts I do follow are showing

### ISSUE THREAD

**Issue by kariohkibox** [dimdenGD/OldTweetDeck#171]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/55408673/95777b3b-0627-4a4b-9e3e-eaa6d7e83215)
Example: I follow MaggieSensei, but do not follow bts_v_tae2019. This reply should not be showing in my main timeline. It does not show in my timeline on the Twitter web version or on the official mobile app, which is the expected behavior. Only noticed this starting very recently, within the last day or so.

**Comment by AnimeAjay** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/87233428/2942118b-6656-4058-a133-9da1d3cfcab9)
Same issue here. I don't follow any of these people being replied to.

**Comment by SmallStrayFox** [comment]
huh just came here to ticket this but seem that everyone is having the same issue.

**Comment by kariohkibox** [comment]
> ok seen some other people on twitter who i dont think are using tweetdeck complaining about the issue. perhaps it's a wider issue than just tweetdeck

Interesting how scattered it is, since it's happening to me on old tweetdeck but not on normal twitter. Silly site

**Comment by SmallStrayFox** [comment]
> > ok seen some other people on twitter who i dont think are using tweetdeck complaining about the issue. perhaps it's a wider issue than just tweetdeck
> 
> Interesting how scattered it is, since it's happening to me on old tweetdeck but not on normal twitter. Silly site

did a bit of digging on the accounts i screenshotted and i suspect they're all using oldtweetdeck, even if they dont explicitly state it in their tweets, so scratch my previous statement, it's probably an oldtweetdeck issue.

**Comment by archeruwu** [comment]
> ok seen some other people on twitter who i dont think are using tweetdeck complaining about the issue. perhaps it's a wider issue than just tweetdeck ![chrome_DctjmP8Tgu](https://private-user-images.githubusercontent.com/13082203/300637100-b9d00b01-29a1-4b64-b1e8-5c17b284d18c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTc2NzUsIm5iZiI6MTcwNjU5NzM3NSwicGF0aCI6Ii8xMzA4MjIwMy8zMDA2MzcxMDAtYjlkMDBiMDEtMjlhMS00YjY0LWIxZTgtNWMxN2IyODRkMThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjMxYThiZmNkNDBlODk5NmY3NDY4NjVjZDAxNzgzMWFkZTg5MWEyMmY1ZjQ4ZmRiMTkzNDFkODJhMGZjZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cbd5YRSODi0x3WQZbbzerArBwN9glUQE_gNiEvuyPU)

![image](https://github.com/dimdenGD/OldTweetDeck/assets/18449883/b26d40b4-1285-410d-87c7-648d06e178cf)
![image](https://github.com/dimdenGD/OldTweetDeck/assets/18449883/a8a75670-e3ce-4e36-80e0-2081fd4cbae3)
![image](https://github.com/dimdenGD/OldTweetDeck/assets/18449883/c5135b90-9cff-4803-9654-57d511fb4eef)
all of these people are using oldtweetdeck

**Comment by SmallStrayFox** [comment]
> > ok seen some other people on twitter who i dont think are using tweetdeck complaining about the issue. perhaps it's a wider issue than just tweetdeck ![chrome_DctjmP8Tgu](https://private-user-images.githubusercontent.com/13082203/300637100-b9d00b01-29a1-4b64-b1e8-5c17b284d18c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTc2NzUsIm5iZiI6MTcwNjU5NzM3NSwicGF0aCI6Ii8xMzA4MjIwMy8zMDA2MzcxMDAtYjlkMDBiMDEtMjlhMS00YjY0LWIxZTgtNWMxN2IyODRkMThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjMxYThiZmNkNDBlODk5NmY3NDY4NjVjZDAxNzgzMWFkZTg5MWEyMmY1ZjQ4ZmRiMTkzNDFkODJhMGZjZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-cbd5YRSODi0x3WQZbbzerArBwN9glUQE_gNiEvuyPU)
> 
> ![image](https://private-user-images.githubusercontent.com/18449883/300706395-b26d40b4-1285-410d-87c7-648d06e178cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDY3NjgsIm5iZiI6MTcwNjYwNjQ2OCwicGF0aCI6Ii8xODQ0OTg4My8zMDA3MDYzOTUtYjI2ZDQwYjQtMTI4NS00MTBkLTg3YzctNjQ4ZDA2ZTE3OGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5MjEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNmM4OGJiZTJiMzRjZGM4YjkyZGU4YzYyMzJlMzRkMWIzY2U2M2NlYzg5YzQ0Y2I2MzRiOTlhZDAzMWRmZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q7qIRL2s80McY3eFP1TWJTEEpyZXOhEriGMmMQoJeCk) ![image](https://private-user-images.githubusercontent.com/18449883/300706533-a8a75670-e3ce-4e36-80e0-2081fd4cbae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDY3NjgsIm5iZiI6MTcwNjYwNjQ2OCwicGF0aCI6Ii8xODQ0OTg4My8zMDA3MDY1MzMtYThhNzU2NzAtZTNjZS00ZTM2LTgwZTAtMjA4MWZkNGNiYWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5MjEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZmY0MDg5MGFkZTYyZTIwZTZhYzYwOGEyYWRkYjM2OTFmMGRiZGI3MDM1M2Q4N2JkZTQ5YjhkOTUyZDMxODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0NnmSq3BEVRA_wtorDcvQ-Pyn8-EymprGUSPY4r8CwQ) ![image](https://private-user-images.githubusercontent.com/18449883/300706620-c5135b90-9cff-4803-9654-57d511fb4eef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDY3NjgsIm5iZiI6MTcwNjYwNjQ2OCwicGF0aCI6Ii8xODQ0OTg4My8zMDA3MDY2MjAtYzUxMzViOTAtOWNmZi00ODAzLTk2NTQtNTdkNTExZmI0ZWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA5MjEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNmVkMzYzYTkxZWQ3MGE4ZmI4NGZiYjcxNzU1OTYyM2FmNzc3YmE0N2FlNWYwNDdhNDA0ODBiZjY2ZjNlYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwpDZestJbul6NHohaSLfP_unsbjizvjuIEar7iMW68) all of these people are using oldtweetdeck

yeah i figured that was the case after my first response. out of interest how are you seeing the twitter app they're using, at a certain point last year didn't that get stripped out?

**Comment by GoldenLumia** [comment]
Same issue as everyone else. If this functionality could be retained as a toggle of sorts like the rate-limit bypass that might be cool as well?

**Comment by dimdenGD** [comment]
Fixed, new release is available

**Comment by dimdenGD** [comment]
There's also a new option for those that want to keep it:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/26517362/84da0ce3-e524-41d0-9746-b344ca89f57d)

**Comment by SmallStrayFox** [comment]
that's amazing, thanks @dimdenGD. gonna increase my patreon tier because of that

**Comment by archeruwu** [comment]
Go on the chrome web store or Firefox Add-on store and search "Return Source Labels"
