### ISSUE TITLE
Seeing replies to people I don't follow on timeline

### ISSUE THREAD

**Issue by Dibface** [dimdenGD/OldTweetDeck#172]
On my home timeline, I've started seeing people whom I follow, tweeting replies to people that I DON'T follow. It's ending up making my timeline a lot more spammy, I'm seeing a much larger volume of incoming tweets because I'm now seeing EVERYONE'S replies, to anyone.

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/171
