### ISSUE TITLE
Replies other than my own from users I follow are streaming into the tweet column of the timeline column.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTweetDeck#173]
I was looking at Old Tweetdeck's timeline and it looked very strange, so I'm reporting it.
As you can see in the image below, the replies of the users I follow are flowing, but it is not only my replies, but also the replies of other users.
I wonder if this means that there is a glitch in the API...?
At any rate, please fix it if you can.
![image](https://github.com/dimdenGD/OldTweetDeck/assets/139020260/728d33c5-72c9-4e8b-864b-45e70aa69854)

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/171
