### ISSUE TITLE
Buttons for displaying long tweets do not appear on Japanese posts.

### ISSUE THREAD

**Issue by lath60** [dimdenGD/OldTweetDeck#174]
There was an update in 3.1.7 to "add a button to show longer tweets", but that button still does not appear on Japanese posts. I have confirmed that it is there for English posts.
Is it possible to have this addressed?
![スクリーンショット 2024-01-30 135320](https://github.com/dimdenGD/OldTweetDeck/assets/52446087/b0853f94-9f5f-48fb-b129-d48354c70000)
![スクリーンショット 2024-01-30 135338](https://github.com/dimdenGD/OldTweetDeck/assets/52446087/ac20c269-1879-43bc-a900-23c6b67b3529)

**Comment by dimdenGD** [comment]
Might be fixed now, please check last version

**Comment by lath60** [comment]
I have confirmed that button is now visible after today's fix, thank you!
