### ISSUE TITLE
No Replies from other users show up on home column when disabling the "Show all replies in home column" option

### ISSUE THREAD

**Issue by NoNameAtAll** [dimdenGD/OldTweetDeck#178]
Tied in part to [Issue 171](https://github.com/dimdenGD/OldTweetDeck/issues/171), the option to disable the "Show all replies in home column" does disable ALL replies. When it's enabled, it continues the behavior that was shown in Issue 171.

Prior to that bug, the only replies that would show up on the home column were from other users I followed. Essentially, only mutuals. It was more fine-tuned than just all users or none.

Is there any way to get the old behavior back? Or, if the "Show all replies in home column" option, when disabled will revert the behavior back to how it was before Issue 171 occurred?

**Comment by z0t0702** [comment]
First, thank you for the repeated fixes.

With the latest fix, the HOME timeline now shows the replies I have made and the replies from accounts I follow. However, the solution is only for logged-in account A. The HOME timeline of the non-logged-in one, account B, still does not show replies sent by account B or received by account B.
Previously, replies sent by account B and replies received from accounts B follows would have shown up in B's HOME timeline.

Of course, if you enable the "Show all replies in home column" option, they will still be shown, but replies to accounts other than the followers will also be shown.

**Comment by dimdenGD** [comment]
> Tied in part to [Issue 171](https://github.com/dimdenGD/OldTweetDeck/issues/171), the option to disable the "Show all replies in home column" does disable ALL replies. When it's enabled, it continues the behavior that was shown in Issue 171.
> 
> Prior to that bug, the only replies that would show up on the home column were from other users I followed. Essentially, only mutuals. It was more fine-tuned than just all users or none.
> 
> Is there any way to get the old behavior back? Or, if the "Show all replies in home column" option, when disabled will revert the behavior back to how it was before Issue 171 occurred?

It doesn't disable all replies for me, only non mutual ones

**Comment by dimdenGD** [comment]
> First, thank you for the repeated fixes.
> 
> With the latest fix, the HOME timeline now shows the replies I have made and the replies from accounts I follow. However, the solution is only for logged-in account A. The HOME timeline of the non-logged-in one, account B, still does not show replies sent by account B or received by account B. Previously, replies sent by account B and replies received from accounts B follows would have shown up in B's HOME timeline.
> 
> Of course, if you enable the "Show all replies in home column" option, they will still be shown, but replies to accounts other than the followers will also be shown.

idk if this is possible to fix at this point

**Comment by NoNameAtAll** [comment]
> > Tied in part to [Issue 171](https://github.com/dimdenGD/OldTweetDeck/issues/171), the option to disable the "Show all replies in home column" does disable ALL replies. When it's enabled, it continues the behavior that was shown in Issue 171.
> > Prior to that bug, the only replies that would show up on the home column were from other users I followed. Essentially, only mutuals. It was more fine-tuned than just all users or none.
> > Is there any way to get the old behavior back? Or, if the "Show all replies in home column" option, when disabled will revert the behavior back to how it was before Issue 171 occurred?
> 
> It doesn't disable all replies for me, only non mutual ones

Seems to be that it works as intended on the primary account using Tweetdeck, but not the attached ones. I'm not seeing threads between mutuals on the secondary accounts unless I enable the ability to see tweets from all users. It's very bizarre.

**Comment by dimdenGD** [comment]
Fixed
