### ISSUE TITLE
Users replying to themselves in non-followee initiated threads appear on home timeline

### ISSUE THREAD

**Issue by alexamacbett** [dimdenGD/OldTweetDeck#180]
Related to either the bugs or the fixes for #171 and maybe #175, replies still appear on the home timeline in situations where they should not (and do not on regular Twitter) in cases where the account you do follow replies to their own tweet that is or is in a reply chain with a reply started by someone you do not follow.

Example:
![image](https://github.com/dimdenGD/OldTweetDeck/assets/8759575/50ab7ca1-7d60-43b5-9677-e12bf56bf288)
I follow @CDisillusion but do not follow @FilmmakerIQ. As shown below, this is a thread started by @FilmmakerIQ replying to @CDisillusion's original post. I don't see CD's reply to FIQ's reply on my home timeline, but I *do* see his second followup reply because it's a reply to himself, even though in this situation it still shouldn't be shown (and regular Twitter doesn't show it).
![image](https://github.com/dimdenGD/OldTweetDeck/assets/8759575/ebac6f1c-357a-49ad-998c-a3f2c0ef1621)

**Comment by dimdenGD** [comment]
Unfortunately, this isn't possible to fix

**Comment by alexamacbett** [comment]
Dang. That's unfortunate. I'd rather hoped there'd be a way of parsing something like "If this is a reply to the account's self _and_ any number one or greater of different unfollowed accounts, but not any other followed accounts; hide it" but I assume you don't have that granular control?

**Comment by dimdenGD** [comment]
As you probably know, what causes this whole bug with replies is that for some reason Twitter now returns them in the API. What I do to fix it is fetch whole list of followed user ids, and if replied user id isnt in list then filter it out. Problem is that Twitter only returns replied user id for only replied tweet, any previous mentions are only supplied as usernames which I don't have data for (only ids)

**Comment by alexamacbett** [comment]
Tragic. Thanks for the effort and the prompt reply at least.
