### ISSUE TITLE
Request, right click menu - May be BTD issue, too

### ISSUE THREAD

**Issue by BKeyport** [dimdenGD/OldTweetDeck#181]
I'd like to see an option added to the right click menu, "Load in Twitter/X" for any tweet/post. this will allow me to reply quickly with GIFs and such as BTD/Tweetdeck doesn't load gifs in the window anymore.

**Comment by dimdenGD** [comment]
You can scroll click on tweet timestamp to open it in twitter

**Comment by BKeyport** [comment]
oh, wow. didn't know that. good to know.
