### ISSUE TITLE
Replies to unfollowed accounts. 

### ISSUE THREAD

**Issue by jordzawada** [dimdenGD/OldTweetDeck#182]
I have two accounts, this could be part of the issue. 

With multiple accounts, replies that normally would not be there are showing up. 

On the "secondary" accounts home timeline, replies made to accounts the second account does not follow appear in the timeline. I think the replies made to accounts the "primary" account follows makes its way into the "secondary" accounts home timeline. 

ex;
Logged in Account A and Account B. A is the main account. 

Account A follows users red, and blue.
Account B follows users yellow and green.

On Account B's home timeline, replies to reds and blues tweets from users yellow or green show up B's timeline even though B does not follow red or blue.

 It may be because A follows red and blue that those replies show up on B's timeline.

**Comment by dimdenGD** [comment]
Fixed
