### ISSUE TITLE
[feature suggestion] hide interactions between people I follow on HOME

### ISSUE THREAD

**Issue by fredericomattos** [dimdenGD/OldTweetDeck#186]
I don't know if it's possible, but it would be great if there was a way to add the ability to hide from HOME when people you follow interact with each other.

For example, I follow @test1 and @test2, so at some point @test1 comments on a post by @test2, this answer appears in the HOME.

If there was a way to hide them, it would make your HOME much cleaner!

**Comment by TopoR** [comment]
Small addition, there also some tricky result after all that reply bug/feature in timeline:
If the user I follow reply to himself inside the thread with others (even if there wasn't anyone who I follow) — I see this tweet in timeline.

At first glance I've managed to "fix" this issue via additional strict check: all mentioned accounts in this tweet must be followed too to see:

```
// reply to someone i follow from someone i follow
follows.includes(t.in_reply_to_user_id_str) &&` 
t.user.following && t.entities.user_mentions.every(user => follows.includes(user.id_str))
```
But need more testing.

**Comment by fredericomattos** [comment]
> Small addition, there also some tricky result after all that reply bug/feature in timeline: If the user I follow reply to himself inside the thread with others (even if there wasn't anyone who I follow) — I see this tweet in timeline.
> 
> At first glance I've managed to "fix" this issue via additional strict check: all mentioned accounts in this tweet must be followed too to see:
> 
> ```
> // reply to someone i follow from someone i follow
> follows.includes(t.in_reply_to_user_id_str) &&` 
> t.user.following && t.entities.user_mentions.every(user => follows.includes(user.id_str))
> ```
> 
> But need more testing.

Hello @TopoR , could you tell me what the code would look like to make it look the way I indicated as a feature request? If so, could you tell me and tell me how I can change in my installed extension?

Sorry for asking this, but I have no knowledge of this area.

**Comment by TopoR** [comment]
@fredericomattos I'm not as good at this too, but at first glance I think I can help at this request at least for now.

First of all you should update to the latest version of unpacked extension.
Next you must activate local mode (there will be no more updates on the fly, and you will be using files from the unpacked extension). Load TweetDeck, open console (F12 while focusing TweetDeck window) and type there:
`localStorage.OTDalwaysUseLocalFiles = 1`
Now every change in the unpacked extension files will be applied on page refresh without uploading extension again.

Now, to the most interesting part, the part of the code you looking for inside «\src\interception.js» around line 400+:

Initial:
```
(
   // reply to someone i follow from someone i follow
  follows.includes(t.in_reply_to_user_id_str) && 
 t.user.following && t.entities.user_mentions.every(user => follows.includes(user.id_str))
) 
```
I think it'll be something like
```
(
 // reply to someone i follow from someone i follow
 t.in_reply_to_user_id_str == t.user.id_str && 
 t.user.following && t.entities.user_mentions.length == 0
)
```
We check that this is self-reply by tweet author
` t.in_reply_to_user_id_str == t.user.id_str`
Then that we following him
` t.user.following`
And that there no more mentioned accounts too (e.g. it is a self-reply, but inside a larger thread where also mentioned other users)
`t.entities.user_mentions.length == 0`

**Comment by fredericomattos** [comment]
@TopoR I would like to thank you immensely for your help, perfectly detailed and intuitive!

Just one last question, in case I want to go back to the standard regarding:
```
localStorage.OTDalwaysUseLocalFiles = 1
```
Should I change from `1` to `0` or is it another definition?

**Comment by dimdenGD** [comment]
Hi! I just added this into the code, @fredericomattos so you dont need to use local files anymore

**Comment by TopoR** [comment]
@dimdenGD thanks!

**Comment by fredericomattos** [comment]
You were magnificent in helping me @TopoR and @dimdenGD , thank you very much!

And @TopoR the feature request I indicated is actually more restrictive, but for general use I see that as it stands now it is much more receptive to everyone!
