### ISSUE TITLE
Fails to login

### ISSUE THREAD

**Issue by hyunsikjeong** [dimdenGD/OldTweetDeck#188]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/5892860/e8c542f3-bbb3-496c-b8bb-e6c5d3d0b885)

Currently it fails to log in with this error log. It seems like certain API endpoints are blocked.
Both `https://api.twitter.com/1.1/tweetdeck/clients/blackbird/all` and `https://api.twitter.com/1.1/tweetdeck/clients` return 404.

**Comment by AnimeAjay** [comment]
Broken in Chrome too. 

Is this the end?

**Comment by Dibface** [comment]
Same errors using Chrome. Login won't work at all.
![image](https://github.com/dimdenGD/OldTweetDeck/assets/149938560/1cff124d-37f6-44e4-9687-83168efc13a8)

**Comment by boilinabag** [comment]
grrrrrrrrr. please help us obi won, you're our only hope...

**Comment by Parrelo** [comment]
With edge i the same

Sorry, something went wrong. Please try again later. More info: [@d1mden](https://twitter.com/d1mden)

**Comment by snowbound** [comment]
I am getting a white layout with only being populated with columns from my account. The search columns fail to load

**Comment by dimdenGD** [comment]
Fixed. Keep in mind that column state is now stored in browser instead of Twitter servers, so everything is reset.

**Comment by EpicLPer** [comment]
@dimdenGD Maybe a very stupid idea, but... could this potentially be stored as a DM sent to yourself in TweetDeck? As in, no servers required or anything, but the client tries to read settings on a new PC from that DM to then restore settings on multiple PCs

**Comment by snowbound** [comment]
FYI when I had to reconfigure the font size I could not select Large size as the credit text and the link to your Please Donate page is overlaid in the font size options area. This is because you added in the option to see all Tweets recently.

**Comment by Parrelo** [comment]
Now is working!! Thank you dimdenGD!!!!!

**Comment by cpwada** [comment]
Will I have to add back my columns every time I close and later reopen Tweetdeck?   My columns do not appear to be saving.

**Comment by culturedniichan** [comment]
> Will I have to add back my columns every time I close and later reopen Tweetdeck? My columns do not appear to be saving.

I can confirm this seems to happen to me. I'm using Firefox if it helps

**Comment by dimdenGD** [comment]
Can you tell your column setup and settings you're using for them?

**Comment by dimdenGD** [comment]
I currently can't reproduce bug with saving columns, it always works fine for me no matter what I do
