### ISSUE TITLE
Chrome: Could not load javascript 'files/notifications.js' for content script

### ISSUE THREAD

**Issue by Kangashark42** [dimdenGD/OldTweetDeck#19]
This is what happens when I select the folder after clicking Load Unpacked in Chrome Extensions:

Error
Could not load javascript 'files/notifications.js' for content script.
Could not load manifest.

**Comment by Kangashark42** [comment]
<img width="507" alt="Screen Shot 2023-08-21 at 2 26 12 PM" src="https://github.com/dimdenGD/OldTweetDeck/assets/44415767/5df7f3b5-c68a-4bb7-9097-2ef88ef35b54">

**Comment by Kangashark42** [comment]
I tried to look, but the "files" folder doesn't allow me to view the contents. It says I dont have permission

**Comment by dimdenGD** [comment]
this is issue with ur computer not extension, grant urself access to viewing files

**Comment by Kangashark42** [comment]
You're righht, changing the permission of the individual files folder granted Chrome the access it needed and it works now. Thanks!
