### ISSUE TITLE
Sorry, something went wrong. Please try again later.

### ISSUE THREAD

**Issue by diopwejepfwo1** [dimdenGD/OldTweetDeck#190]
When running Twitter Deck on Chrome, a window like this pops up.
![deck](https://github.com/dimdenGD/OldTweetDeck/assets/160085147/1c369400-4561-409a-9c99-d0f34741f2aa)

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/188
