### ISSUE TITLE
Anyone esle 

### ISSUE THREAD

**Issue by ItsBluey** [dimdenGD/OldTweetDeck#191]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/290efff1-b4d3-4be1-a427-2a29840a7213)
didnt have this until rn now was working just fine and i reinstalled still

**Comment by hofleverancier** [comment]
Same here, 3.2.3 seems to have been broken.

**Comment by surapunoyousei** [comment]
No. Some of TweetDeck APIs are deleted by X.

Please delete this post. Do not waste maintainer's time

**Comment by mattweeden** [comment]
Getting the same issue

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/188
