### ISSUE TITLE
Manifest version 2

### ISSUE THREAD

**Issue by PadoLee71** [dimdenGD/OldTweetDeck#192]
![스크린샷 2024-02-15 131636](https://github.com/dimdenGD/OldTweetDeck/assets/142639496/e127c188-734c-475d-bd0f-bee62da9ae71)

Is a disruption in support for Manifest version 2 related to a login failure?

**Comment by surapunoyousei** [comment]
No. Some of TweetDeck APIs are deleted by X.

Please delete this post. Do not waste maintainer's time
