### ISSUE TITLE
Opening a photo that doesn’t have same height and width will make it shrink

### ISSUE THREAD

**Issue by TomBonnot** [dimdenGD/OldTweetDeck#20]
It’s a weird but that when we open a post with a photo, instead of just being there staying fixed, it shrinks fast. 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/35734114/2bb0be2a-75e1-4cdf-8c95-2820315f10bc)
![image](https://github.com/dimdenGD/OldTweetDeck/assets/35734114/7de0e761-a529-4cab-bd17-cd2fd60900d4)
less than 3 seconds between those two screenshots

**Comment by TomBonnot** [comment]
Solved it @dimdenGD Thank you, closing it !

**Comment by dlinv773** [comment]
This issue is still happening in the lastest version.

**Comment by TomBonnot** [comment]
refresh the page, it has happened to me too but I don’t know why I did refresh and everything was fine. Could you try it again ? Otherwise I re open the bug report
