### ISSUE TITLE
Everything is gone

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [dimdenGD/OldTweetDeck#206]
Hi, today I woke up to see my tweetdeck completely reset. Light theme, all the columns are gone, all the spacing settings are gone, everything. Is this known issue? Did I do something wrong?

**Comment by dimdenGD** [comment]
did you know about tweetdeck state being switched to browser storage? did it randomly happen after you recreated them again ever since it happened

**Comment by dimdenGD** [comment]
yep

**Comment by Michal-Szczepaniak** [comment]
Thanks for help
