### ISSUE TITLE
OldTweetdeck User Home Column API is broken?

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTweetDeck#210]
No matter how much I reload, delete the cache, and even re-download, the column tweets will not load with the following console error.
Is this a bug?
Used Version : 3.4.0
![image](https://github.com/dimdenGD/OldTweetDeck/assets/139020260/13779694-ebe9-4730-9fa3-f07a16175c15)
![image](https://github.com/dimdenGD/OldTweetDeck/assets/139020260/33fbb950-4484-4f6a-aa2a-03e69380d6ef)

**Comment by dimdenGD** [comment]
Can't reproduce

**Comment by EZ2Alpa** [comment]
I updated Chrome and the symptoms are still the same. The console frequently gives several undefined errors after fetching tweets every time I load them. However, some other accounts were loading fine. It is possible that the problem is with the API of the home column of each account. Is it possible that this bug happens only to me...? !
 [image](https://github.com/dimdenGD/OldTweetDeck/assets/139020260/4136d6df-ced1-4d09-b7e1-468394cd8c43)

**Comment by EZ2Alpa** [comment]
I've got some error information in the extensions management, so I'll raise this one as well... 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/139020260/25d89095-3fe7-48c8-aa3e-fed31a760a4a)
