### ISSUE TITLE
Not Working On MyPal 68.13.7

### ISSUE THREAD

**Issue by theanthonydavenport** [dimdenGD/OldTweetDeck#218]
I cannot import the addon/extension on the MyPal Browser, Version: 68.13.7
<img width="340" alt="Screenshot 2024-03-26 at 11 13 30" src="https://github.com/dimdenGD/OldTweetDeck/assets/99144439/9ce80857-e22e-4bf9-ba6a-bc99f36ae409">

**Comment by dimdenGD** [comment]
Unsupported
