### ISSUE TITLE
Keybinds are randomly broken

### ISSUE THREAD

**Issue by haxibami** [dimdenGD/OldTweetDeck#22]
Pressing `n` sometimes redirect to `https://tweetdeck.twitter.com/compose/tweet`. Perhaps keybinding for Web App or X Pro (beta) is loaded.

**Comment by Wintiger0222** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/24960466/17081cf7-a7a4-4d4c-bc72-088e0aaa88f8)
X Pro loads many java script on another body.
This seems to cause this issue (Especially, https://abs.twimg.com/gryphon-client/client-web/vendor.080895ba.js does)
Make sure that this JavaScript is not loaded when the page loads.

There are users who blocked this script with some adblocker and solved
(https://twitter.com/CMRbada/status/1693920427108872222)

**Comment by dimdenGD** [comment]
I've updated repo and releases. Now extension blocks URLs starting with `/gryphon-client/`
