### ISSUE TITLE
Home Column Not Showing For You Feed Tweets

### ISSUE THREAD

**Issue by theanthonydavenport** [dimdenGD/OldTweetDeck#224]
OldTweetdeck
<img width="318" alt="Screenshot 2024-03-30 at 22 42 46" src="https://github.com/dimdenGD/OldTweetDeck/assets/99144439/f1c30130-a14a-42fb-ad0f-65266505a4fc">

X Pro (Better Known As Regular Tweetdeck)
<img width="362" alt="Screenshot 2024-03-30 at 22 41 18" src="https://github.com/dimdenGD/OldTweetDeck/assets/99144439/7be73093-387f-4608-a22d-4335507b7916">

**Comment by dimdenGD** [comment]
wont be added
