### ISSUE TITLE
OldTD 2.0.4 breaks the BetterTD Again…

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTweetDeck#23]
In 2.0.1~3 I could use it again by clearing the cache using CTRL+SHIFT+R, 
but since 2.0.4 I cannot reuse it using that. Please fix this urgently.

**Comment by dimdenGD** [comment]
BetterTweetDeck often doesn't work when you press CTRL+SHIFT+R, but when you press F5 few times it starts working

**Comment by EZ2Alpa** [comment]
I see...sometimes hitting F5 in a row works. Thank you very much!
