### ISSUE TITLE
X.com migration has broke a lot of padding.

### ISSUE THREAD

**Issue by archeruwu** [dimdenGD/OldTweetDeck#236]
This same issue happens on OldTwitter.

Whenever you try to load either extension, it just leads to a blank white page.

As of this report, it's only in Australia, so using a VPN would be the easiest way to debug

**Comment by psylenced** [comment]
It should still work, if you manually type:

https://twitter.com/i/tweetdeck

What I've noticed is videos don't seem to play, and all links are now using the shortened domain.

**Comment by VirtuallyJesse** [comment]
Starting experiencing this today. I've not noticed anything completely breaking, but there are a few UI & padding issues now. Namely when you click on media to enlarge it, there's a fixed secondary window behind the media that it's centered upon, which never used to exist.

**Comment by archeruwu** [comment]
Updated post title, a LOT of padding got broken
![image](https://github.com/dimdenGD/OldTweetDeck/assets/18449883/f1c0a3c3-8bcc-4feb-a35a-3c4510ea377e)
![image](https://github.com/dimdenGD/OldTweetDeck/assets/18449883/e263635b-e303-4bb7-a164-e8513fe776e4)

**Comment by theanthonydavenport** [comment]
<img width="333" alt="Screenshot 2024-05-17 at 13 01 09" src="https://github.com/dimdenGD/OldTweetDeck/assets/99144439/b86dd36d-c573-44d1-a458-146edf02131e">

**Comment by dimdenGD** [comment]
Should be fixed
