### ISSUE TITLE
add-on cant be verified on Firefox 111.01 (fedora 38)

### ISSUE THREAD

**Issue by Asteriadeath** [dimdenGD/OldTweetDeck#237]
tried to install oldtweetdeck on fedora, cant be verified.

**Comment by archeruwu** [comment]
Go to about:config, set "xpinstall.signatures.required" to false, then try to install

**Comment by byungyoonc** [comment]
Same problem on Firefox 126.0 (Windows 11). Even after setting `xpinstall.signatures.required` to `false`, I cannot install the addon with the following message.

```
This add-on could not be installed because it has not been verified.
```

I tried restarting the browser after setting the variable, but it still fails.

**Comment by dimdenGD** [comment]
You need to use Firefox for Developers
