### ISSUE TITLE
I can't move to TweetDeck（I solved it, but I will leave the method and leave it for a while.）

### ISSUE THREAD

**Issue by tarookun** [dimdenGD/OldTweetDeck#238]
Even if you access https://twitter.com/i/tweetdeck , the page of "Log in with your Twitter Account" will be displayed.

**Comment by tarookun** [comment]
If tweetdeck is now open, don't log out from Twitter.
If you log out, you will be redirected as described above even if you log in again.

**Comment by BKeyport** [comment]
It appears that the main links have all moved to x.com - breaking things all over the place. I'm logged out on my home computer, so I'm stuck.

**Comment by ItsBluey** [comment]
yea @dimdenGD needs to update pls

**Comment by tarookun** [comment]
https://twitter.com/d1mden/status/1791407084279320676

According to the content tweeted by Dimden earlier
1. Disable theoldtweetDeck
2. Access https://twitter.com/i/tweetdeck in that state. Log in to Twitter on that page.
3. Enable OldtweetDeck when you log in and access https://twitter.com/i/tweetdeck again.

**Comment by acabrelles** [comment]
Hello, I am attempting to follow these steps but I am not succeeding. It keeps saying "This page doesn't exist, Try making another search.". I do not know if I am doing something wrong? I am not getting to any page that forces me to log in, in the first place.

**Comment by tarookun** [comment]
Looking at the browser history, it was redirected to https://pro.twitter.com/ in my case, and it seems that I logged in from there.
Note that it is not https://x.com/i/premium_sign_up

**Comment by Lacerta-agilis** [comment]
being redirected to https://x.com/i/tweetdeck where the addon doesnt work. permissions to be updated.

**Comment by t5k6** [comment]
Elon Musk: All core systems are now on [X.com](https://X.com)

**Comment by dimdenGD** [comment]
Should be fixed

**Comment by BKeyport** [comment]
Everything's working, but the redirect from tweetdeck.twitter.com
(naturally, I think) - Update bookmarks to x.com/i/tweetdeck and it's fine.
