### ISSUE TITLE
I try login tweetdeck but.. x.com is not working

### ISSUE THREAD

**Issue by Cookieun** [dimdenGD/OldTweetDeck#240]
![캡처](https://github.com/dimdenGD/OldTweetDeck/assets/170096589/e88bf9fa-69c5-43bd-9a46-870ad9835be9)
first i try but this page and i check 'log in'

![캡처2](https://github.com/dimdenGD/OldTweetDeck/assets/170096589/c591f1ce-4d1f-4548-b443-90d73cd1cc04)

i can't log in and use tweetdeck

i think we need to put 'x.com ' in the authority

i use whale and chrome
and i use OldTweetDeck 3.2.3 ver

**Comment by Lacerta-agilis** [comment]
same here
i tried to update manually the site permissions with adding x.com, tweetdeck.x.com etc but anyway login page redirects me to https://x.com/login?hide_message=true&redirect_after_login=https%3A%2F%2Fx.com%2Fi%2Ftweetdeck%3Fvia_twitter_login%3Dtrue which is not opening

**Comment by Cookieun** [comment]
I changed the version and entered this address, and I succeeded
I couldn't figure out which was the right answer, but I think you can try both!
https://twitter.com/x/migrate?tok=eyJlIjoiL2hvbWUiLCJ0IjoxNzE1OTQ4NzY1faCW9mXCCvgLtnLL3LAEQSo%3D

**Comment by siubb** [comment]
> I changed the version and entered this address, and I succeeded I couldn't figure out which was the right answer, but I think you can try both! https://twitter.com/x/migrate?tok=eyJlIjoiL2hvbWUiLCJ0IjoxNzE1OTQ4NzY1faCW9mXCCvgLtnLL3LAEQSo%3D

Works for me too !! Thank you.

**Comment by iamkeq** [comment]
> > I changed the version and entered this address, and I succeeded I couldn't figure out which was the right answer, but I think you can try both! https://twitter.com/x/migrate?tok=eyJlIjoiL2hvbWUiLCJ0IjoxNzE1OTQ4NzY1faCW9mXCCvgLtnLL3LAEQSo%3D
> 
> Works for me too !! Thank you.

Changed to version 3.6.2?  I did this and the mentioned URL just keeps reloading over and over

**Comment by Cookieun** [comment]
I chose 3.6.2 and I logged in from x and pressed that address
Then it still connected to site x
Let's go to the https://twitter.com/i/tweetdeck' site. It's confirmed

**Comment by kakakaya** [comment]
I've updated 3.6.2, but got message: `Found. Redirecting to https://x.com/i/tweetdeck` on https://twitter.com/i/tweetdeck .

And, it says error message as below:

![image](https://github.com/dimdenGD/OldTweetDeck/assets/3298037/65b989e2-7876-4754-9b99-5a602338be8f)
