### ISSUE TITLE
Tweetdeck Opening Issue 

### ISSUE THREAD

**Issue by theanthonydavenport** [dimdenGD/OldTweetDeck#241]
Shown here, this is what happens when I go to: https://[twitter.com/i/tweetdeck](https://twitter.com/i/tweetdeck)
<img width="604" alt="Screenshot 2024-05-17 at 13 07 43" src="https://github.com/dimdenGD/OldTweetDeck/assets/99144439/5d019fa6-bcfc-4cc3-bf49-4d1718c1229f">

**Comment by dimdenGD** [comment]
Just go to x.com/i/tweetdeck

**Comment by theanthonydavenport** [comment]
That didn't work.

**Comment by theanthonydavenport** [comment]
> Just go to x.com/i/tweetdeck
<img width="1729" alt="Screenshot 2024-05-19 at 00 20 52" src="https://github.com/dimdenGD/OldTweetDeck/assets/99144439/047a8cd6-b1d6-45db-8cd4-bb4ca208022f">
It still doesn't work.
