### ISSUE TITLE
Unable to send a Tweet

### ISSUE THREAD

**Issue by sandsand1551** [dimdenGD/OldTweetDeck#242]
![capture](https://github.com/dimdenGD/OldTweetDeck/assets/144031388/2838a331-e6aa-4d93-a1e5-702597656ace)

I did the 3.6.0 update because the layout was messed up, but after the update the layout was still messed up. So I cleared my cache and cookies, and since then the layout is fine, but no more tweets are being sent. Other functionality is fine.

**Comment by dimdenGD** [comment]
Fixed, refresh page

**Comment by sandsand1551** [comment]
Thank you!
