### ISSUE TITLE
Layout reset 

### ISSUE THREAD

**Issue by AnimeAjay** [dimdenGD/OldTweetDeck#249]
Updated yesterday for the redirect issue however just today my layout has reset. 

Any idea why this would have happened?

**Comment by dimdenGD** [comment]
Because url was changed to x.com

**Comment by dimdenGD** [comment]
Technically, it's possible since data is still stored in your browser. But there's no special script or easy way to get it out anymore. In future I recommend to export your state when you make changes to it.
