### ISSUE TITLE
URL bar now visible since X.com update

### ISSUE THREAD

**Issue by Neobond** [dimdenGD/OldTweetDeck#252]
![18-05-2024 20 41 11](https://github.com/dimdenGD/OldTweetDeck/assets/42996358/d5c7ac6a-e23a-4251-968e-a17a6dd2c1ae)

Is there any way to get rid of this ugly URL bar with the web address in it?

Appreciate all your hard work with keeping this alive!

**Comment by Neobond** [comment]
Better Tweetdeck also doesn't work anymore :(

**Comment by archeruwu** [comment]
change your chrome web-app to x.com/i/tweetdeck instead of twitter.com

**Comment by Neobond** [comment]
Thanks!

**Comment by danielzapp** [comment]
> change your chrome web-app to x.com/i/tweetdeck instead of twitter.com

Sorry for the question, but how do I do that?

**Comment by Neobond** [comment]
> > change your chrome web-app to x.com/i/tweetdeck instead of twitter.com
> 
> Sorry for the question, but how do I do that?

You will have to "uninstall" the Tweetdeck shortcut, then go to x.com/i/tweetdeck and then choose to install it again (in Chrome under main menu > "Save and share"). Your current shortcut to Tweetdeck still points to twitter.com.

**Comment by danielzapp** [comment]
Thanks! It worked!

**Comment by janny8282** [comment]
Seems that x.com has changed something again. Old Tweetdeck not working anymore here.

**Comment by janny8282** [comment]
Yes, today its working again. Maybe late problem at x.com.

**Comment by janny8282** [comment]
Now not working again.

**Comment by archeruwu** [comment]
Update to latest release

**Comment by Neobond** [comment]
![18-08-2024_ 120703](https://github.com/user-attachments/assets/e86d60ca-16f5-4dcc-9e59-3330cb300ac4)

This empty space appears when OldTweetDeck starts before Chrome (on Windows 11 boot).

The current workaround is to close OldTweetDeck, start Chrome then start OldTweetDeck again and the space between the titlebar and tweet columns is no longer there, odd bug for sure!
