### ISSUE TITLE
A combination of video and image only show the image

### ISSUE THREAD

**Issue by SpicyChickenCurry** [dimdenGD/OldTweetDeck#255]
Sometimes a post has both videos and images, it only shown the images in oldtweetdeck. 
I just confirm this happens for all posts.

**Comment by archeruwu** [comment]
This has been a bug since before TweetDeck was even killed off, the pre-elon Twitter team never updated TweetDeck to support multiple media types in 1 tweet. 

Nothing really anyone can do to fix it 🤷

**Comment by SpicyChickenCurry** [comment]
I see. Thank you!
