### ISSUE TITLE
Sidebar labels get stuck to the top of the page

### ISSUE THREAD

**Issue by TheClassic36** [dimdenGD/OldTweetDeck#26]
Sidebar labels get stuck to the top of the page and stack on top of each other after hovering over the sidebar icons.

OTD v2.0.4 on Chrome. This was also an issue with v1, but occured less frequently.

![Screenshot_1](https://github.com/dimdenGD/OldTweetDeck/assets/24751415/80c6b9c9-fdcd-47a9-9558-4c724a4b39bd)

**Comment by andykamezou** [comment]
+1 to this issue. It happens only when the sidebar is in the Collapsed state.

The tooltip was not removed on mouse out, so every time user hovers the cursor over the sidebar icon, more of these divs will remain loaded: 
![20230823 104751](https://github.com/dimdenGD/OldTweetDeck/assets/6763353/e0e3f640-2aaa-4f5f-89c7-0d4f138274ac)

**Comment by TheClassic36** [comment]
This appears to be fixed in v3.0.2. I'll leave this issue open until someone else can also confirm.

**Comment by TheClassic36** [comment]
It's confirmed then! Closing this now.
