### ISSUE TITLE
All icons and images fail to load/display

### ISSUE THREAD

**Issue by Sakirth** [dimdenGD/OldTweetDeck#260]
Essentially any and all icons and images do not load. This includes icons on the sidebar (see image down below) but also extends to people's avatar on the timeline, images in tweets and the like/RT/comment icons below tweets. 

I'm using the latest release 3.6.4. and I'm on stable version 122.0 of Firefox (please don't judge me for not using nightly). This wasn't an issue yet with 3.6.2, hopefully that helps.

![fail](https://github.com/dimdenGD/OldTweetDeck/assets/117391550/faaeb89c-2000-4fcb-aa01-c58cf8408230)

**Comment by katabame** [comment]
I tried reproduce the issue, but it doesn't reproduced.
I used flatpak version of firefox (v126.0) and OldTweetDeck v3.6.4

Could you check which url you're opening?

https://x.com/i/tweetdeck is correct url for now.
because Twitter moved their url to `x.com` from `twitter.com`

![image](https://github.com/dimdenGD/OldTweetDeck/assets/9818101/79bd88a5-794c-4aeb-ab2c-e08e5f871922)

**Comment by Sakirth** [comment]
> I tried reproduce the issue, but it doesn't reproduced. I used flatpak version of firefox (v126.0) and OldTweetDeck v3.6.4
> 
> Could you check which url you're opening?
> 
> https://x.com/i/tweetdeck is correct url for now. because Twitter moved their url to `x.com` from `twitter.com`
> 
> ![image](https://private-user-images.githubusercontent.com/9818101/332752643-79bd88a5-794c-4aeb-ab2c-e08e5f871922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzYzMDMsIm5iZiI6MTcxNjM3NjAwMywicGF0aCI6Ii85ODE4MTAxLzMzMjc1MjY0My03OWJkODhhNS03OTRjLTRhZWItYWIyYy1lMDhlNWY4NzE5MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTEwNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRmYTgzZTk0OTlhNGYyODgyMzcyMGMwYjA0ZTM3MzgyZGYyYTQ0N2QzNjU1MmRjMzBjY2JlODM4OWRlMTlmOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fq--g_bN4FvUaiLvEGuhzYcGVS635yt3ehf1onZwbgQ)

Oh, this is a bit awkward. I tested it with a fresh install and it worked fine. Turns out old cookies were causing the issue! I should probably have thought of that in advance. Thanks for thinking along!

I'll close this now as there is no longer an issue.
