### ISSUE TITLE
Importing saved settings

### ISSUE THREAD

**Issue by LoFi1978** [dimdenGD/OldTweetDeck#264]
Is it still possible to import my saved settings (OTDState.json), and if so, what would I have to do?
How can I save them?
Any help appreciated.

**Comment by katabame** [comment]
Hello @LoFi1978!

Yes, you can still import (and export) `OTDState.json`

To import/export, open Settings window via right-bottom ⚙ cog icon > settings
then click Import state or Export state button.

![image](https://github.com/dimdenGD/OldTweetDeck/assets/9818101/e5104f8b-d4b2-473c-a89d-5e40e4b0b734)
![image](https://github.com/dimdenGD/OldTweetDeck/assets/9818101/8157e3f3-ccf2-425c-bb62-613b958e2632)

**Comment by LoFi1978** [comment]
Thanks for your answer. 
Problem is this Import/Export option showed up last time for me in version 3.5.5. (I'm on 3.6.4 now)
I also realised there are only two option left now under Settings>Mute: "Words or phrases" and "Tweet Source"

![Zwischenablage02](https://github.com/dimdenGD/OldTweetDeck/assets/170500118/ee90e2ec-2ad6-4b9c-951c-a6014308f54f)

**Comment by idav** [comment]
I'm on 3.6.4 under Chrome and have the import-export function. All I can suggest is close app, clear cache, reload extensions and restart app.

**Comment by katabame** [comment]
> ![Zwischenablage02](https://github.com/dimdenGD/OldTweetDeck/assets/170500118/ee90e2ec-2ad6-4b9c-951c-a6014308f54f)
> 

import/export button is located at bottom of general settings.
i can see scrollbar at your general setting window, so you may need scroll it down.
