### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by been9312** [dimdenGD/OldTweetDeck#265]
I was told I could ignore this error message and it became a closed issue, but every time I turn on chrome I get the error and the tweetdeck page doesn't come up. I have to clear the error and refresh the tweetdeck page every time, what can I do to reduce this hassle?

Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.

{
    "name": "OldTweetDeck",
    "description": "Returns old TweetDeck, for free!",
    "version": "3.6.2",
    "manifest_version": 2,
    "homepage_url": "https://github.com/dimdenGD/OldTweetDeck",
    "permissions": [
        "webRequest",
        "webRequestBlocking",
        "webNavigation",

**Comment by dimdenGD** [comment]
3.6.2 is old version
