### ISSUE TITLE
New bug - Twitter (X) now interferes with loading sometimes

### ISSUE THREAD

**Issue by BKeyport** [dimdenGD/OldTweetDeck#268]
hey - getting a "This page doesn't exist" frequently enough to be annoying when loading. Will start the loading process, showing the circle spinning, then gives the error or loads tweetdeck.

**Comment by UberPlexCa** [comment]
I'm seeing the same after refreshing the page.   
![image](https://github.com/dimdenGD/OldTweetDeck/assets/66147998/94d6609c-c8de-4e03-a298-79efbd236ca1)

**Comment by UberPlexCa** [comment]
CTRL+F5 cleared it up

**Comment by BKeyport** [comment]
That just makes it show up more on my end.

**Comment by katabame** [comment]
I'd like to clarify which version of OldTweetDeck using, and which url you're accessing.

Current latest version of OldTweetDeck is `v3.6.4`
and its changelog mentioning about injection.
Please check you're using latest (`v3.6.4`) version

> Fixed OldTweetDeck failing to inject due to changes in Twitter code.
https://github.com/dimdenGD/OldTweetDeck/releases/tag/v3.6.4

Also Twitter is changing their url to `x.com` from `twitter.com`
so the Tweetdeck url should be https://x.com/i/tweetdeck

I'm currently using latest (`v.3.6.4`) version of OldTweetDeck and accessing to https://x.com/i/tweetdeck, not occuring any issue.

**Comment by BKeyport** [comment]
I'm using 3.6.2, didn't get a notification about 3.6.4. Will push up to
that.
