### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

### ISSUE THREAD

**Issue by p3P4** [dimdenGD/OldTweetDeck#27]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
{
  "name": "Old TweetDeck",
  "description": "Returns old TweetDeck, for free!",
  "version": "2.0.2",
  "manifest_version": 2,
  "homepage_url": "https://github.com/dimdenGD/OldTweetDeck",
  "permissions": [
    "webRequest",

**Comment by dimdenGD** [comment]
Ignore the message, it works fine
