### ISSUE TITLE
Can no longer paste images into tweet field

### ISSUE THREAD

**Issue by alexamacbett** [dimdenGD/OldTweetDeck#277]
Version 3.6.4

In actual old tweetdeck, as well as previous releases of OldTweetdeck, it was possible to add an image in the clipboard to a tweet (and possibly other media too) by pasting (through Ctrl+V or the context menu) while the tweet field was active. This would cause the pasted image to be added as if it were uploaded using the "Add Images Or Video" button and was available in all cases except when quoting a tweet (because development of original tweetdeck never caught up to the twitter update that added media quoting and didn't allow it under any circumstances).

At least since the 3.6.4 update if not slightly before, it is no longer possible to paste images into the field this way. Attempting to do so does nothing.

**Comment by MUNENEDENNIS** [comment]
I am experiencing the exact same issue. Have you found any workaround or solution?

**Comment by dimdenGD** [comment]
use bettertweetdeck
