### ISSUE TITLE
Likes Tab No Longer Working

### ISSUE THREAD

**Issue by Nuri2424** [dimdenGD/OldTweetDeck#281]
Version of OldTweetDeck 3.6.4 (Chrome) is no longer able to sync Likes of any user (could be due to recent X changes). Am not able to see my own likes, nor likes of anyone I follow even if they've made their likes public again (loading screen keeps syncing). Re-downloaded/re-installed with no fixes; other software up-to-date and other columns working perfectly/syncing correctly.

**Comment by rokiwi111222** [comment]
Same with Firefox

**Comment by Noname36342** [comment]
I am having the same issue, but i do not think the reason is the last changes made on Twitter, cause after twitter hide likes it wass still working, even 9 hours ago was still working.

**Comment by dimdenGD** [comment]
its gone forever

**Comment by rokiwi111222** [comment]
Even for our own likes? That sucks
