### ISSUE TITLE
Likes column no longer loads

### ISSUE THREAD

**Issue by VelvetShadows** [dimdenGD/OldTweetDeck#282]
As of June 14 the Likes column no longer loads any content, I can access my likes as usual through the website but cannot see them in TweetDeck. Presumably related to Twitter making likes private as I believe that was scheduled to occur as of the 14th as well.

**Comment by dimdenGD** [comment]
its gone

**Comment by Hellothereilikediscord** [comment]
So does that mean you're not going to work on a fix at all and its gone forever?

**Comment by StormTetris** [comment]
He will make a community-sourced version of likes soon. Think of it being similar to the Youtube Dislike Extension, after Youtube disabled the dislike count around 2021.
