### ISSUE TITLE
Fix the botton "likes"  of the other profile PLISS!!!

### ISSUE THREAD

**Issue by Karolin0213** [dimdenGD/OldTweetDeck#299]
OldTweetDeck
3.6.4 version

In this version it's not possible see the likes in the other profile, the page stay "loading"!!
![captire](https://github.com/dimdenGD/OldTweetDeck/assets/174294141/a4b95a00-86c6-499c-a74d-051c6451ff73)

**Comment by katabame** [comment]
since Twitter made likes private, the API to retrieve likes are gone. due to this, impossible to fix the likes tab.

see also: #280 #281 #282 #283 #284 #285

**Comment by Karolin0213** [comment]
but how is it possible? I agree with this user, the option to see the likes was still working after "X" changed the code:
https://github.com/dimdenGD/OldTweetDeck/issues/281#issuecomment-2167549051 

I wish you could please review it to see if something can be done about it or fix that bug in the next new version.
