### ISSUE TITLE
Any plans to release backend code?

### ISSUE THREAD

**Issue by derreka** [dimdenGD/OldTweetDeck#3]
Do you plan to release the files you are currently hosting on your server so more tech savvy users can run the app either locally or on a server of their own?

Also thanks for both this and OldTwitter they're awesome and so are you ^^

**Comment by psylenced** [comment]
Just adding to this, could you place those files in a ```wwwroot/``` folder in the package so people have easy access to self host.

Also add ```tweetdeck.dimden.dev``` as a variable in the node packing to allow easy replacement (in case of future updates to this).

**Comment by kairusds** [comment]
> List of files used: https://tweetdeck.dimden.dev/index.html https://tweetdeck.dimden.dev/vendor.js https://tweetdeck.dimden.dev/bundle.js https://tweetdeck.dimden.dev/bundle.css

those are the bundled files, it doesn't show the actual source code

**Comment by dimdenGD** [comment]
> those are the bundled files, it doesn't show the actual source code

Twitter never provided actual code for TweetDeck, I just took their bundled files

**Comment by kairusds** [comment]
> > those are the bundled files, it doesn't show the actual source code
> 
> Twitter never provided actual code for TweetDeck, I just took their bundled files

ah got it

**Comment by dimdenGD** [comment]
I've recoded extension into manifest v2. Now no external server is required
