### ISSUE TITLE
After sometime of accessing the oldtweetdeck it is redirecting me to this url https://x.com/i/tweetdeck

### ISSUE THREAD

**Issue by barmanshantanu** [dimdenGD/OldTweetDeck#305]
Include version of extension. **Make sure you're using last version before submitting a bug report! Check releases page before reporting anything!**

**Comment by katabame** [comment]
Hello @barmanshantanu 
1stly, please read issue template. please include your version and etc. next time.

2ndly, this is intended behavor I think.
Did you read the readme?
![image](https://github.com/dimdenGD/OldTweetDeck/assets/9818101/1d702d02-6fb6-4632-8809-ab03d5c754af)

**Comment by ericwc30060** [comment]
> Hello @barmanshantanu 1stly, please read issue template. please include your version and etc. next time.
> 
> 2ndly, this is intended behavor I think. Did you read the readme? ![image](https://private-user-images.githubusercontent.com/9818101/346473956-1d702d02-6fb6-4632-8809-ab03d5c754af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzUxNzYsIm5iZiI6MTcyMDYzNDg3NiwicGF0aCI6Ii85ODE4MTAxLzM0NjQ3Mzk1Ni0xZDcwMmQwMi02ZmI2LTQ2MzItODgwOS1hYjAzZDVjNzU0YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTgwNzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2NjdkOWZjNDhjMmViYzI2Zjk2ODA4ZDZhYjMwYjM5ZDg3N2Q3NWM3NzczNzc1NjRjNjJmYmIyZjgxNzBjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rgdxa0ldt1WR2XULIk4HJ8V-FmjOFe3XrcsrP5tyCng)

Katabame,

    being nasty towards barmanshantanu is not helpful.  I have tried versions 3.6.4 and 3.6.5 according to your instructions in the past hour and neither work.  Instead of just blaming us, some friendly advice would appreciated.

Thanks

**Comment by katabame** [comment]
> > Hello @barmanshantanu 1stly, please read issue template. please include your version and etc. next time.
> > 2ndly, this is intended behavor I think. Did you read the readme? ![image](https://private-user-images.githubusercontent.com/9818101/346473956-1d702d02-6fb6-4632-8809-ab03d5c754af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MzUxNzYsIm5iZiI6MTcyMDYzNDg3NiwicGF0aCI6Ii85ODE4MTAxLzM0NjQ3Mzk1Ni0xZDcwMmQwMi02ZmI2LTQ2MzItODgwOS1hYjAzZDVjNzU0YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTgwNzU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2NjdkOWZjNDhjMmViYzI2Zjk2ODA4ZDZhYjMwYjM5ZDg3N2Q3NWM3NzczNzc1NjRjNjJmYmIyZjgxNzBjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rgdxa0ldt1WR2XULIk4HJ8V-FmjOFe3XrcsrP5tyCng)
> 
> Katabame,
> 
> ```
> being nasty towards barmanshantanu is not helpful.  I have tried versions 3.6.4 and 3.6.5 according to your instructions in the past hour and neither work.  Instead of just blaming us, some friendly advice would appreciated.
> ```
> 
> Thanks

then what can I say? not reading readme and issue template, no detailed information, no reproduce steps.
tons of people doesn't read readme or issue template, and similar issue is opened long ago. which means didn't search anything about related topic.

so then I just mentioned about issue template and readme, if isn't solved by that, you can just another comment with more detailed description.

blaming me is also not helpful isn't it? if I'm dimden you didn't say about like that.

**Comment by ericwc30060** [comment]
Katabame,

   The other day I was frustrated and wasn't nice to you.  I am sorry
