### ISSUE TITLE
Chrome - "Please check your network connection and refresh TweetDeck."

### ISSUE THREAD

**Issue by ZReese23** [dimdenGD/OldTweetDeck#306]
Currently on the latest version of Chrome Canary - v128 - and I've been having an issue for the past week where I keep getting the error message shown in the title. Tried to clear my cache and cookies, logging out and in, and nothing works. It works just fine on Firefox, so I'm guessing it's a Chrome-specific issue? I'm getting an "ERR_UNSAFE_REDIREC" error in the console, too.

**Comment by katabame** [comment]
Hello @ZReese23 
To be confirm, which URL you're accessing to?
if you're accessing to `https://tweetdeck.com`, then try `https://x.com/i/tweetdeck` insteaed.

also seems you're familiar with chrome dev tools, I suggest clear redirect cache with following
1. Open DevTools on TweetDeck page
2. make ✅ at `Network` > `Disable cache`
3. Reload the page
4. if works, make un✅ at `Network` > `Disable cache`

**Comment by ZReese23** [comment]
> Hello @ZReese23 To be confirm, which URL you're accessing to? if you're accessing to `https://tweetdeck.com`, then try `https://x.com/i/tweetdeck` insteaed.
> 
> also seems you're familiar with chrome dev tools, I suggest clear redirect cache with following
> 
> 1. Open DevTools on TweetDeck page
> 2. make ✅ at `Network` > `Disable cache`
> 3. Reload the page
> 4. if works, make un✅ at `Network` > `Disable cache`

Hello there, thanks for the help. I tried "https://x.com/i/tweetdeck" and the checkmark on "Disable cache" and both gave me the same error. If there's something in particular in the console that could help identify it, please let me know.

**Comment by katabame** [comment]
Hi @ZReese23! Thanks for response.
I'm sorry; I can't assist furture more I ran out my knowledge. (which means dimden knows more about this maybe)

for reproducing this issue, I want to be clear which version of extension are you using. (as far as I know you I only heard your chrome version)
also is it happenens on Chrome stable or Chrome beta? if on stable/beta worked, I assume Chrome changed something.

**Comment by ZReese23** [comment]
> Hi @ZReese23! Thanks for response. I'm sorry; I can't assist furture more I ran out my knowledge. (which means dimden knows more about this maybe)
> 
> for reproducing this issue, I want to be clear which version of extension are you using. (as far as I know you I only heard your chrome version) also is it happenens on Chrome stable or Chrome beta? if on stable/beta worked, I assume Chrome changed something.

Ah, thanks anyway. I just tried it on the latest version of Chrome Beta (v 127.0.6533.43) and it ran just fine. Seems like something changed with v 128. I'm also using the latest version of the extension. I had the previous version still installed, but tried updating it to the latest and had the same problem.

**Comment by ZReese23** [comment]
Noting here that it appears to be working again on build 128.0.6601.0.
