### ISSUE TITLE
I can't download on Firefox the addon

### ISSUE THREAD

**Issue by furry72** [dimdenGD/OldTweetDeck#307]
Hello dimdenGD, i tried install your addon in my Firefox and pop a error can't installed

**Comment by katabame** [comment]
Hello @furry72.
To be clear, firstly we doesn't provide official firefox addon on firefox addon store. if you installed from addon store, please uninstall it and re-install manually.

Here's a our offical document for installation on firefox (nightly). Could you follow the steps again?
https://github.com/dimdenGD/OldTweetDeck?tab=readme-ov-file#nightly--developer-edition

if the still error occures, please provide screen shot the poped up error or paste logs (if there's) for investigate your situation.

thanks.

**Comment by dimdenGD** [comment]
Follow instructions exactly, they work
