### ISSUE TITLE
Twitter figured it out...

### ISSUE THREAD

**Issue by BKeyport** [dimdenGD/OldTweetDeck#31]
Twitter has figured it out, I'm getting the premium prompt again. :(

**Comment by ricky-wong** [comment]
It still works for me, but I did see it briefly once on d4d9eb8.

Due to the way the extension works, it's pretty expected to see random flashes of stuff occasionally.

**Comment by BKeyport** [comment]
I got it back, had to clear cookies for the last 24 hours to do it, but...
