### ISSUE TITLE
page doesnt exist

### ISSUE THREAD

**Issue by smilodooon** [dimdenGD/OldTweetDeck#310]
Unable to load tweetdeck keeps saying Hmm...this page doesn’t exist. Try searching for something else.

![image](https://github.com/user-attachments/assets/9a2b0f81-a8f6-40a4-8ef4-23544d00c84d)

**Comment by dimdenGD** [comment]
that means plugin is not installed

**Comment by smilodooon** [comment]
indeed, it was disable and i dont remember disabling it, thanks!
