### ISSUE TITLE
Unable to Paste Images in OldTweetDeck Version 3.6.5

### ISSUE THREAD

**Issue by MUNENEDENNIS** [dimdenGD/OldTweetDeck#311]
When I try to paste an image into the tweet field, nothing happens. This problem occurs consistently across different systems and browsers. 

1. Copy an image to the clipboard.
2. Activate the tweet field by clicking on it.
3. Attempt to paste the image using Ctrl+V or the context menu.

The image should be inserted into the tweet as if it were uploaded via the "Add Images Or Video" button but in this case No image is added when attempting to paste it into the tweet field.

Please check this out.

**Comment by MUNENEDENNIS** [comment]
You can also check out this other post: https://github.com/dimdenGD/OldTweetDeck/issues/277

**Comment by dimdenGD** [comment]
duplicate

**Comment by MUNENEDENNIS** [comment]
hey @dimdenGD I'm not a bot I'm actually going through that issue bro please if you can try and sort it out. thank you for the work you do.

**Comment by MUNENEDENNIS** [comment]
copying and pasting images is impossible you can try it yourself and see.

**Comment by dimdenGD** [comment]
try using bettertweetdeck

**Comment by MUNENEDENNIS** [comment]
![Screenshot 2024-07-26 215033](https://github.com/user-attachments/assets/be9161a2-918b-4909-a57f-85b9c3b4911f)
they shut it down

**Comment by dimdenGD** [comment]
https://github.com/dimdenGD/BetterTweetDeck/releases

**Comment by MUNENEDENNIS** [comment]
![image](https://github.com/user-attachments/assets/fc87dcaf-5c82-40e0-9820-2c7968e4a705)

THANK YOU SIR.

**Comment by MUNENEDENNIS** [comment]
![yes-sir-yes-boss](https://github.com/user-attachments/assets/47b8a370-5800-4f43-a97b-42fd22af0346)


THANK YOU SIR !

**Comment by MUNENEDENNIS** [comment]
So @dimdenGD appreciate all your help.

I have one final question: since the account I am managing is on X Premium is there a way to extend the character limit for my tweets or is this beyond your control?

Thank you!

**Comment by MUNENEDENNIS** [comment]
They should have you at X as an Engineer you just get what the people want

**Comment by dimdenGD** [comment]
its not possible

**Comment by MUNENEDENNIS** [comment]
Sorry to bother you again @dimdenGD  but I have one last issue. Direct Messages (DM) column images are not loading. Videos load fine but images don't appear at all. Even when I click on messages with images no preview is shown and the images do not load.

Thanks so much for your help!
