### ISSUE TITLE
Retweets Failing Intermittently

### ISSUE THREAD

**Issue by Rakkzi** [dimdenGD/OldTweetDeck#312]
Version: 4.11.3 / 3.6.5 (Latest)
Not sure if this is just a me problem, but for the last 3 days or so when I try and retweet something, usually the "Retweet this to your followers?" popup will hang once the Retweet button is pressed, similar to if you've already retweeted that post previously to the same account. Closing the popup and hitting the retweet button again sometimes works, other times I have to reopen it 3 or 4 times for it to successfully go through. Reinstalled the extension and updated to the latest version and it hasn't changed anything. The button turns green as if it was successfully retweeted, but if you click through to the post it goes back to being grey. Happens with all my accounts. Console is getting spammed with this, not sure if it's relevant:
![Screenshot3_30](https://github.com/user-attachments/assets/a3aa55e7-0830-4058-8463-6d9f94ccc8a6)

**Comment by WhereTheTimeWent** [comment]
Had the same thing. It worked again yesterday, but I didn't retweet much. I have BTD installed.
I didn't thoroughly test it, but I think this only happened with one account, which is my main account / the first one I logged into TweetDeck with.

**Comment by naanlizard** [comment]
Happens to me all the time, hope it's an easy fix

**Comment by IFofPlanetune** [comment]
Have encountered a similar issue where Retweets don't work approximately 90% of the time on the first attempt. The error messages in the console do not seem to appear, however the response from the server to the "create_retweet" call looks as follows:

`{
    "errors": [
        {
            "message": "Authorization: This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later. (226)",
            "locations": [
                {
                    "line": 5,
                    "column": 3
                }
            ],
            "path": [
                "create_retweet"
            ],
            "extensions": {
                "name": "AuthorizationError",
                "source": "Client",
                "code": 226,
                "kind": "Permissions",
                "tracing": {
                    "trace_id": "---"
                }
            },
            "code": 226,
            "kind": "Permissions",
            "name": "AuthorizationError",
            "source": "Client",
            "tracing": {
                "trace_id": "---"
            }
        }
    ],
    "data": {}
}`

Could be related or a completely separate bug though

**Comment by dimdenGD** [comment]
I don't know what causes this, I compared the requests and they seem to be identical

**Comment by dimdenGD** [comment]
refresh tab and try retweeting now, maybe fixed

**Comment by Rakkzi** [comment]
> refresh tab and try retweeting now, maybe fixed

Looks like it is, hasn't failed on me yet. Thank you!
