### ISSUE TITLE
cant view my own likes?

### ISSUE THREAD

**Issue by elimelim** [dimdenGD/OldTweetDeck#316]
just spinning circle cant view my likes? maybe to do with the new public settings since june. on latest version

**Comment by cmj** [comment]
I know this has been brought up numerous times in the past, but there is an endpoint to view your own favoriters.

`https://api.twitter.com/graphql/mDc_nU8xGv0cLRWtTaIEug/Favoriters`

I messed around with Nitter quite a bit when 'likes' were semi-removed a few months ago. Just to see what was happening and what still worked, I was able to view my own likes from bots on Twitter. (Nitter is not an interactive frontend; this was to just test endpoints)

Here is an example, still working today that shows favoriters on your posts: 

 ![](https://i.imgur.com/d8bMFju.png)

**Comment by dimdenGD** [comment]
fixed
