### ISSUE TITLE
Refreshing page causing "pay me" page to load.

### ISSUE THREAD

**Issue by SilentPrayeCG** [dimdenGD/OldTweetDeck#32]
Refreshing tweetdeck page cause it behave as if tweetdeck opened without extension - it's load regular twitter and do pop up window with "pay for subscription" message.

**Comment by ItsBluey** [comment]
you have go to https://tweetdeck.twitter.com/ and keep trying eventually it will work also reinstalling helps but @dimdenGD needs to fix alot of bugs

**Comment by SilentPrayeCG** [comment]
Forgot to mention, it's works ok, kinda, it's seems buggy, tho legacy tweetdeck loads, but if i refresh page it ask to pay, so I need type tweetdeck.twitter.com again to refresh it.

**Comment by SilentPrayeCG** [comment]
After updating both extension they seems to be working ok.
And page is refreshing ok now. I guess we can close this thread.
