### ISSUE TITLE
[4.0.0] Extension failed to load

### ISSUE THREAD

**Issue by Lusiiky** [dimdenGD/OldTweetDeck#320]
Hello,

I get the following error when I try to load the extension:
```
Extension failed to load

File: C:\Program Files\BraveSoftware\OldTweetDeckChrome

Error: ruleset.json: Internal error while parsing rules.
Unable to load manifest file.
```

![image](https://github.com/user-attachments/assets/2bb120ce-3530-41c1-9fad-0dc177eeb135)

**Extension version:** 4.0.0

**Browser:** Brave _[Version 1.68.137 Chromium: 127.0.6533.100 (Official Build) (64 bits)]_

I'll stay with version 3.6.8 in the meantime ^^'

Thank you!
Lusiiky

**Comment by dimdenGD** [comment]
Someone reported they could fix this by changing permissions of ruleset.json file on their system

**Comment by Lusiiky** [comment]
@dimdenGD 
> Someone reported they could fix this by changing permissions of ruleset.json file on their system

OH TRUE!
Indeed... as I had set the folder in the same place as the Brave installation, despite read access to the plugin folder, there was no total control/modification, cause Administrator folder.
I just authorized full control to Users and that's it... sorry!
