### ISSUE TITLE
Tweetdeck doesn't want to load

### ISSUE THREAD

**Issue by Pandafyyy** [dimdenGD/OldTweetDeck#323]
Tweetdeck doesn't want to load, i try to reinstall tweetdeck and i have the last version. 
![Capture d'écran 2024-08-13 092400](https://github.com/user-attachments/assets/857c915e-aca2-4f74-b7c8-66584f9666ce)

**Comment by dimdenGD** [comment]
too many user columns, ure rate limited

**Comment by Pandafyyy** [comment]
I tried with just one column but it still doesn’t work, and yesterday i has
5 users column and it worked

**Comment by dimdenGD** [comment]
because you're rate limited now. use list columns instead
