### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vMidway** [dimdenGD/OldTweetDeck#328]
Not really an issue or a feature request just a question and I don't know where to ask else so hope it's fine I do it here.
In settings there's an option called "Enable rate limit bypass (OldTweetDeck)" should that be turned on or is it dangerous like could my Twitter be banned for doing it or something?

**Comment by dimdenGD** [comment]
you can turn it on if columns are not loading and turn it off again if they stop loading again. havent heard of anyone being banned for using it

**Comment by vMidway** [comment]
> you can turn it on if columns are not loading and turn it off again if they stop loading again. havent heard of anyone being banned for using it

How would I know when it stops loading? Doesn't it in the first place stop loading allowing me to see new tweets?😁

**Comment by dimdenGD** [comment]
it means it either doesnt load tweets at all or doesnt show any new tweets

**Comment by vMidway** [comment]
> it means it either doesnt load tweets at all or doesnt show any new tweets

Okay thank you😁
