### ISSUE TITLE
Sorry, we couldn't retrieve user NAME - That user does not exist

### ISSUE THREAD

**Issue by vMidway** [dimdenGD/OldTweetDeck#332]
Newest version 4.02 being used and I keep getting this message "Sorry, we couldn't retrieve user NAME - That user does not exist" when searching up a user's name and clicking on it, but when I click on a users name in the "Home" column it opens the user no problem
And no the user isn't deactivated cause I can open it with no problem on normal X/Twitter

**Comment by dimdenGD** [comment]
Fixed
