### ISSUE TITLE
LOGIN ERROR

### ISSUE THREAD

**Issue by alyson1980** [dimdenGD/OldTweetDeck#335]
Good evening, could someone help me pls? I always used tweetdeck and suddenly it stopped out of nowhere! Yes, IT IS updated and it is Windows 7. The first screen is at https://x.com/i/tweetdeck The second is the extension error screen. Can someone explain it to me? (I have TD on another PC and it's ok but on the laptop it stopped out of nowhere  on this screen)

HELP ME PLEASE I AM AT THE DICTATORSHIP OF BRASIL!!!

![tw](https://github.com/user-attachments/assets/a7431be4-a38c-4749-a7f2-a13715cf0b3e)

![tw](https://github.com/user-attachments/assets/2c804fce-abac-4256-93e2-2b815d6382aa)

**Comment by alyson1980** [comment]
PLEASE SOMEBODY HELP ME!!!

**Comment by katabame** [comment]
Hello @alyson1980, firstly, please calm down for smooth troubleshooting.
To be clarify, which version of chrome and oldtweetdeck you are using.

Chrome's version can be checked via `chrome://settings/help`
![image](https://github.com/user-attachments/assets/b61d867f-6193-4c11-90c6-e001ebeeca22)

OldTweetdeck's version can be checked via `chrome://extensions/`
![image](https://github.com/user-attachments/assets/0cc5a45d-a8e0-42db-a289-15dbda28e4c3)

**Comment by alyson1980** [comment]
...mine is windows 7 and stopped out of nowhere

I got another PC but win10 and its working fine...



________________________________
De: 本田珠彩 ***@***.***>
Enviado: terça-feira, 3 de setembro de 2024 01:57
Para: dimdenGD/OldTweetDeck ***@***.***>
Cc: alyson1980 ***@***.***>; Mention ***@***.***>
Assunto: Re: [dimdenGD/OldTweetDeck] LOGIN ERROR (Issue #335)


Hello @alyson1980<https://github.com/alyson1980>, firstly, please calm down for smooth troubleshooting.
To be clarify, which version of chrome and oldtweetdeck you are using.

Chrome's version can be checked via chrome://settings/help
image.png (view on web)<https://github.com/user-attachments/assets/b61d867f-6193-4c11-90c6-e001ebeeca22>

OldTweetdeck's version can be checked via chrome://extensions/
image.png (view on web)<https://github.com/user-attachments/assets/0cc5a45d-a8e0-42db-a289-15dbda28e4c3>

**Comment by katabame** [comment]
Windows 7 is already end of life(aka end of support), so I think Google Chrome on windows 7 doesn't support some sort of features needed by OldTweetDeck.

If you're using v4.x of OldTweetDeck, how about rolling back to v3.x of OldTweetDeck?

https://github.com/dimdenGD/OldTweetDeck/releases/tag/v3.6.8

**Comment by alyson1980** [comment]
oh i didnt knew that!! worked on 368 but no btd...
![image](https://github.com/user-attachments/assets/38e669f0-0a01-4254-b56e-df2fedc3cb80)

**Comment by alyson1980** [comment]
ok it GOT btd

**Comment by katabame** [comment]
good to hear that! happy tweeting!🎉

**Comment by alyson1980** [comment]
thank u so muuuuuch!!

**Comment by katabame** [comment]
@dimdenGD this issue can be closed
