### ISSUE TITLE
Home tab isn't working with most resent version (and older versions)

### ISSUE THREAD

**Issue by blahxd** [dimdenGD/OldTweetDeck#339]
Home tab isn't loading ![2e10o](https://github.com/user-attachments/assets/e09d617b-0a36-4023-b343-2a55fc2c8479)

Edit: seems I hit tweet limit even with "Enable rate limit bypass" turned on but I'm still having the same home tab issue on an alt account

Edit 2: The home tab loads after leaving tweetdeck open for ~15 minutes but the same issue happens after refreshing the page

**Comment by katabame** [comment]
this happened official Twitter web, so I think temporary Twitter side issue.
