### ISSUE TITLE
Search Columns seems not working anymore

### ISSUE THREAD

**Issue by Psebcool** [dimdenGD/OldTweetDeck#34]
Loading loop message only on search columns. Others columns like List and Follows still work.

**Comment by Akiwave** [comment]
"User" columns don't work either.

**Comment by emmanu888** [comment]
Same here. I have my doubts whether that can be fixed though as that's always been an API problem prior to Twitter sunsetting Legacy Tweetdeck.

**Comment by etui-null** [comment]
It looks to be an API 403 error. 

Probably due to this if I had to guess
https://twitter.com/API/status/1693760591503266165
> For those still using our v1.1 API endpoints 🗣️
> 
> As part of our ongoing effort to modernize and transform our API platform, we are deprecating some of our v1.1 endpoints and asking you to migrate to the v2 equivalents. These deprecations will allow us to continue building support for the latest X features with our v2 API.
> 
> For more information including endpoints, timing, and how to migrate, visit here👇
> [http://bit.ly/xforumdev](https://t.co/swGHDprqLN)

**Comment by perigozin** [comment]
It was good while it lasted, it was kinda surprising that this worked at all, the engineering team at X is laughable but I think they finally fixed it. We'll have to pay or just get used to the regular X.

Tip: with Vivaldi browser you can lay up to 4 tabs side by side giving a TweetDeck'ish feel.

**Comment by TheAGames10** [comment]
I have not been able to load in some of my columns anymore, even after re-installing the extension.

**Comment by ZenofyMedia** [comment]
Even if you are paying for Twitter Blue, Search and User columns no longer work.

**Comment by Whirblewind** [comment]
As Zenofy said, this happened pre-shutoff, too, and not just to Old/Legacy users.

**Comment by perigozin** [comment]
It was working this morning

**Comment by Psebcool** [comment]
> It was good while it lasted, it was kinda surprising that this worked at all, the engineering team at X is laughable but I think they finally fixed it. We'll have to pay or just get used to the regular X.
> 
> Tip: with Vivaldi browser you can lay up to tabs side by side giving a TweetDeck'ish feel. https://www.naporitansushi.com/vivaldi-tweetdeck-recreate/

It's the best solution to be "free" against X subscription I mean, I tried to do it with Chrome with "Tab Resize" extension, but your browser seems better for that 👍

**Comment by forestpassineau** [comment]
Having this issue this morning... Was working perfectly up till now. Tried updating to 2.0.5 and issue still exists. Up till now all columns loaded without issue but this morning many of my normal user profile colums no longer load and just continue to spin saying loading but nothing happens. I even have twitter blue paid version and many user columns do not load and are just left at the spining loading blank column that never loads. Tried uninstalling and reinstalling the extension multiple times along with on different browsers along with different computers.  Nothing works.. The new tweetdeck X Pro really is aweful so even though I am a twitter blue user I still really want the old tweetdeck UI. If all collumns loaded all would be happy! haha

**Comment by Psebcool** [comment]
> It was good while it lasted, it was kinda surprising that this worked at all, the engineering team at X is laughable but I think they finally fixed it. We'll have to pay or just get used to the regular X.
> 
> Tip: with Vivaldi browser you can lay up to tabs side by side giving a TweetDeck'ish feel. https://www.naporitansushi.com/vivaldi-tweetdeck-recreate/

Works fine with Vivaldi browser :)
I use [Modern Scrollbar](https://chrome.google.com/webstore/detail/modern-scrollbar/bgfofngpplpmpijncjegfdgilpgamhdk) and [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) extensions.

In Stylebot, here is the code to hide the left sidebar : 
`/*removing sidebar column*/
div[data-testid="sidebarColumn"] {
  font-weight: 100;
  font-style: normal;
  display: none;
}
div[data-testid="DMDrawer"] {
  display: none;
}
/*横幅が〇px以下の時、サイドバー非表示*/
@media screen and (max-width: 370px) {
    header {
        display: none !important;
    }
}`

**Comment by dimdenGD** [comment]
I was expecting this to happen, and I had a plan to just make interception for requests and route them to new APIs, and then parse results to old format. I've made a interception module, but unfortunately I'm currently stuck at issue with preflight request, Twitter either redirects it or fails it (from my attempts so far).

If anyone wants to try to help me with this, check out [interception](https://github.com/dimdenGD/OldTweetDeck/tree/interception) branch. There's new `files/interception.js` file, also with some commented out changes in `background.js` which were my attempts to make preflight request work.

**Comment by dimdenGD** [comment]
I figured it out, stay tuned

**Comment by ItsBluey** [comment]
works now thanks @dimdenGD. for everyone click download zip and install the releases tab is not updated yet  
![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/9605af72-e417-44b6-ae1f-396aed85e421)

**Comment by dimdenGD** [comment]
I released the update! https://github.com/dimdenGD/OldTweetDeck/releases/tag/v3.0.0

**Comment by TheAGames10** [comment]
Columns stopped working again. :(

**Comment by TheAGames10** [comment]
> > Columns stopped working again. :(
> 
> They seem to be working fine for me. Did you make sure to download the updated code?

Yep, but Columns are still not loading.

**Comment by etui-null** [comment]
> Yep, but Columns are still not loading.
Can you be a bit more specific? What type of column? Search, Notifications, Home, Activity, User; all are currently working for me.

**Comment by TheAGames10** [comment]
> > Yep, but Columns are still not loading.
> 
> Can you be a bit more specific? What type of column? Search, Notifications, Home, Activity, User; all are currently working for me.

Basically, all the user columns I have as well as search column(s).

**Comment by Rooooooobert** [comment]
Same here under 3.0.2. These columns load: Home, Notifications, Lists, Messages, Activity and Trending. All others don't.

**Comment by dimdenGD** [comment]
You're almost definitely hitting rate limit error, either too many rows open or scrolling too much, idk

**Comment by Rooooooobert** [comment]
Seems probable. in FF (stable/temp) I have 16 Colums.
In Edge (other acc) I only have 4 and they still all load ...

**Comment by forestpassineau** [comment]
I was also running into collums not loading and upon refresh of browser still wouldnt load.  then waiting a bit sometimes causes them to load again and at times not.  Bigger issue for me currently is it seems columns that seem to load correctly do not load timely. there is a big delay as in multiple minutes between the time when a user submits a tweet and i see it on my phone to when tweetdeck actually shows the tweet as well.

**Comment by 501stRookie** [comment]
> You're almost definitely hitting rate limit error, either too many columns open or scrolling too much, idk

How many columns would cause this error? I have multiple columns for users and have issues with them not loading as well.

**Comment by snowbound** [comment]
I reduced the columns myself and it seemed to work for a couple of days and now after the computer being turned off for 8 hours the two search columns, one for me and for another user are simply spinning circles

**Comment by TheAGames10** [comment]
> I reduced the columns myself and it seemed to work for a couple of days and now after the computer being turned off for 8 hours the two search columns, one for me and for another user are simply spinning circles

Yea, something tells me the rate limit thing isn't the problem, since I went back to Tweetdeck and then after one single refresh to test out another extension or even restart Chrome, most of the columns are spinning circles again.

**Comment by dimdenGD** [comment]
Have you used normal Twitter meanwhile? They use same endpoints now so maybe you've used up your rate limit on normal Twitter already

**Comment by snowbound** [comment]
With me even leaving the computer powered off for 8 hours did not help. Tweetedeck failed to populate 2 search columns I have configured Tweetdeck for my own posts and another user. Then 2 hrs later I discovered the columns were fully populated. It seems that perhaps that day I had displayed the previous tweets from other users and exceeded the rate limit for 12 hours.

**Comment by TheAGames10** [comment]
The 3.0.5. update is out, the columns are currently loading in correctly this time (for now, at least), but one thing I do not like:

The user columns I have are also showing the tweets the specified users replied to by themselves/separately as well as the actual replies from the users.

I'll attach an image to show what I am talking about, These columns I am showing are both mine as well as another user I follow/enjoy, and it's really strange seeing random tweets in my column along with replies to those random tweets, it's honestly filling up those columns unnecessarily:

![Capture](https://github.com/dimdenGD/OldTweetDeck/assets/111199398/fff4d489-8c6f-40e4-8f4a-188219c002f7)

**Comment by Akiwave** [comment]
> The 3.0.5. update is out, the columns are currently loading in correctly this time (for now, at least), but one thing I do not like:
> 
> The user columns I have are also showing the tweets the specified users replied to by themselves/separately as well as the actual replies from the users.

Yeah, same issue. I fixed if for myself by using the setting to filter out other users' tweets. 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/130281859/39fbf18c-96eb-4eda-a64e-deaba9a90225)

**Comment by dimdenGD** [comment]
Fixed

**Comment by TheAGames10** [comment]
Oh great, I got rate limited and now I cannot use Twitter nor TweetDeck anymore!!! THAT IS SUCH AN EW, TBH!
