### ISSUE TITLE
new install on chrome error

### ISSUE THREAD

**Issue by boilinabag** [dimdenGD/OldTweetDeck#340]
v4.3 getting an error on the console. new install so i am not sure why it isnt working, yet on my desktop it seems fine with brave. thanks.
![Screenshot 2024-09-06 4 22 43 PM](https://github.com/user-attachments/assets/03fe5058-7385-4256-9c61-b7f20a8c308b)

**Comment by dimdenGD** [comment]
you can ignore errors if it works

**Comment by boilinabag** [comment]
sorry about this post. stupid update. chrome changing to v3. update fixed it. 

hey, i hope your doing well, you got us lurkers concerned about you and what's happening. we're with you in spirit. stay safe....
