### ISSUE TITLE
Popup notifications not working

### ISSUE THREAD

**Issue by yodos1** [dimdenGD/OldTweetDeck#35]
Old Tweetdeck had sound and desktop notifications available in the Preferences option for each column.  These options are still shown but do not work even when selected and permissions "allowed" in the browser settings.  The sounds sometimes work but the popups do not.  Not sure why.  Ive tried this with Edge and Chrome browsers.  Thanks.

**Comment by dimdenGD** [comment]
Notifications are coming from server and are impossible to recreate
