### ISSUE TITLE
'Rate limit exceeded' issue

### ISSUE THREAD

**Issue by good-70** [dimdenGD/OldTweetDeck#350]
안녕하세요! 올드 트윗덱을 감사히 사용하고 있는 유저입니다. 

최근 팀에 새로운 계정을 추가한 뒤, [Link another account you own]를 눌러 팀에 추가한 계정을 추가하려고 하면 'Rate limit exceeded'라는 문구가 출력되며 아무런 변화도 없는데 혹시 해당 이슈에 대한 해결법이 있을까요?

항상 좋은 하루 되시길 바랍니다.

**Comment by dimdenGD** [comment]
https://github.com/dimdenGD/OldTweetDeck/issues/259#issuecomment-2281786253

**Comment by good-70** [comment]
*번역기를 사용했습니다. 
[Manage team]에서 새로운 계정을 추가하는 것은 성공했습니다. 관리 권한을 admin으로 수정도 완료했습니다!

하지만 위의 단계를 마친 것 만으로는 '새로 추가한 계정'의 탭을 추가할 수 없는 것으로 알고 있습니다.
그래서 [Link another account you own] 단계에서 '새 계정'을 추가하려고 했습니다. 하지만 캡쳐의 화면이 출력되며 '새 계정'을 추가할 수 없는 것으로 확인됩니다. 

*I used a translator.
Adding a new account in [Manage team] was successful. You have also modified admin privileges to admin!

However, I understand that just completing the above steps does not allow us to add the tab of 'newly added accounts'.
So I tried to add a 'new account' in the [Link another account you down] phase. However, the screen of the capture is printed and it is confirmed that I can't add a 'new account'.

![image](https://github.com/user-attachments/assets/b8412e3f-2028-40d5-9b55-3f02046f0705)
