### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by Sia-L** [dimdenGD/OldTweetDeck#353]
When I tried logging in to connect a new account to TweetDeck, I only saw 'Rate limit exceeded' and the window no longer worked.
![hg; hj;gh;](https://github.com/user-attachments/assets/4f4e5af2-bf7e-4f1f-81e3-3d33adee1bf3)

**Comment by katabame** [comment]
https://github.com/dimdenGD/OldTweetDeck/issues/259#issuecomment-2281786253
