### ISSUE TITLE
Only some columns loading

### ISSUE THREAD

**Issue by forestpassineau** [dimdenGD/OldTweetDeck#36]
Was working great until now but just this morning it fails to load many of the user profile columns I have setup that were loading fine yesterday.  Tried updating to newest 2.0.5 version and still only loads some of the user profile columns and many are left unpopulated?

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTweetDeck/issues/34

**Comment by dimdenGD** [comment]
Released new version, update!
