### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ItsBluey** [dimdenGD/OldTweetDeck#361]
![image](https://github.com/user-attachments/assets/6a2bf7d0-943d-44de-8454-9be1c3bbca40)

**Comment by dorox** [comment]
![image](https://github.com/user-attachments/assets/24bf652b-0431-4800-8c4a-657c4e2e1268)
Same here. Chrome version 131.0.6778.86

**Comment by dimdenGD** [comment]
Fixed https://github.com/dimdenGD/OldTweetDeck/releases/tag/v4.0.4
