### ISSUE TITLE
Cannot add an account with "Link another account you own"

### ISSUE THREAD

**Issue by enorikarura** [dimdenGD/OldTweetDeck#370]
Version 4.0.4 , issue persists using BetterTD or not.(on Chrome,mac)

When I click on the left sidebar -> “Link another account you own” -> Continue, I get the error `{“errors”:[{“message”: “Bad Authentication data”, “code”:215}]}`, I cannot add an account.
<img width="804" alt="スクリーンショット 2024-12-17 0 18 07" src="https://github.com/user-attachments/assets/4a09707d-a45d-4f96-a670-d8970a47ea85" />

I tried reinstalling the extension, but that did not help.
(I am translating from Japanese, so the text may be incorrect.)

**Comment by dimdenGD** [comment]
https://github.com/dimdenGD/OldTweetDeck/issues/259#issuecomment-2281786253

**Comment by enorikarura** [comment]
Thank you!
