### ISSUE TITLE
Tweetdeck doesn't load

### ISSUE THREAD

**Issue by Martin1995** [dimdenGD/OldTweetDeck#4]
as the title says
![image](https://github.com/dimdenGD/OldTweetDeck/assets/12379684/410d98df-0021-4eb1-bdd8-ab51db08d4e2)

it doesn't matter if you stay in developer mode after installing the addon, I just get a loading screen and the errors on the screenshot.

I don't know if it's a bug with vivaldi

**Comment by nero-0** [comment]
Same here.

**Comment by lcreed** [comment]
Can confirm brave is reporting that twitter refuses to connect

**Comment by ghostriderz7** [comment]
I am now experiencing this, if I try in incognito.

**Comment by GoldenLumia** [comment]
It is still working for me on Vivaldi, but I'm wondering if BetterTweetdeck is fixing my issue in the background.

**Comment by dimdenGD** [comment]
Works fine for me

**Comment by ghostriderz7** [comment]
> Works fine for me
This is what I am getting on Chrome (incognito)

Also I am finding that I have to turn it off, and back on to let it properly load within the main browser with it hitting limits every 50 minutes. It wont load with my main account I use for Chrome, as I have several accounts and such on there. It leads me to the log in screen. 

![Screenshot 2023-08-18 180644](https://github.com/dimdenGD/OldTweetDeck/assets/140808544/9e165f41-dc05-4701-94c7-981d799403c9)

**Comment by Fifczej** [comment]
Doesn't work on Brave, twitter rejects connection while trying to log in

**Comment by p182** [comment]
On Brave, try to disable "Shields", it seems fix "twitter.com refuses to connect" issue for me

**Comment by VictorAlvarez7** [comment]
> On Brave, try to disable "Shields", it seems fix "twitter.com refuses to connect" issue for me

Not working for me. Still "refuses to connect".

**Comment by ignmunoz** [comment]
Works with Chrome for me, It happened to me the 'twitter.com refuse to connect' thing too. First I have to log in twitter / X and then go to tweetdeck.twitter.com and press the 'Log In' button

**Comment by Martin1995** [comment]
I was logged in at the same time as it happened, I'm currently on my phone, but will try it again later

**Comment by Fifczej** [comment]
> Doesn't work on Brave, twitter rejects connection while trying to log in

Worked for me when I disabled shields, thanks

**Comment by lcreed** [comment]
Thank you!  disabling shields worked!

**Comment by IouSASTU** [comment]
I had this problem until I stopped blocking third party cookies on the tweetdeck url.

**Comment by dimdenGD** [comment]
I've updated extension to work completely differently (no more external server required), install latest version and check if it works now for you

**Comment by lcreed** [comment]
New version is again not working on brave for me, even with shields down.  I'm getting redirected back to twitter with the send me money page
![image](https://github.com/dimdenGD/OldTweetDeck/assets/734957/51ec1ac9-2c78-497f-aecc-7c3d3419527d)

**Comment by dimdenGD** [comment]
Rollback to https://github.com/dimdenGD/OldTweetDeck/releases/tag/v1.0.2 if it doesn't work for you, idk why it doesn't work for some people

**Comment by jlitz** [comment]
working fine for me on Opera    someone said sign out of  twitter and  back  in then open tweetdeck     dunno

**Comment by ricky-wong** [comment]
I just threw 3637ac8b8d2bd05dde6ecdb00f0ed259f8b51794 into a fresh dedicated Chrome user and it worked.
Then updated to d049a7cb6c7590d1820bfcf08bc92656f248b428 and it still worked.
Maybe try using a new Chrome profile? That busts a lot of cache/cookies problems.

(I was already working fine on 3f4a9a4addf115a20a5ef99a486f22a12da832b3)

**Comment by dimdenGD** [comment]
Yeah it seems that https://github.com/dimdenGD/OldTweetDeck/commit/3637ac8b8d2bd05dde6ecdb00f0ed259f8b51794 fixed the issue with 2.0, works for everyone I asked

**Comment by lcreed** [comment]
All good on Brave with shields up now.  thanks!!!

**Comment by Martin1995** [comment]
I've captured an error of the old version before I've updated
![image](https://github.com/dimdenGD/OldTweetDeck/assets/12379684/16324826-02ef-465c-9d8c-06b49c639923)

the new 2.0.1 version works💖
![image](https://github.com/dimdenGD/OldTweetDeck/assets/12379684/5644fcbd-cd57-42fe-affe-a22a65fc8e94)

I will close the issue now, thank you💖💖💖💖

**Comment by Martin1995** [comment]
I've just noticed this after closing the issue, I don't know if you're already aware of it
![image](https://github.com/dimdenGD/OldTweetDeck/assets/12379684/33b6f650-e65e-48b6-8efb-f26b3c791692)

**Comment by dimdenGD** [comment]
This message means nothing and Google is lying

**Comment by Martin1995** [comment]
ah, ok👌
