### ISSUE TITLE
Tab title "page not found"

### ISSUE THREAD

**Issue by jankete** [dimdenGD/OldTweetDeck#44]
I'm using version 3.0 of this plugin under the latest chrome. It is working fine, but for the tweetdeck tab, the title is named as "Seite nicht gefunden / X" (page not found)

![image](https://github.com/dimdenGD/OldTweetDeck/assets/22338766/75e9df4f-1c2d-4fcf-aa4f-78b4a52cf4a2)

**Comment by dimdenGD** [comment]
There's a new update, check if it still happens

**Comment by jankete** [comment]
Solved in 3.0.2
