### ISSUE TITLE
Massive scrollbars and page not found in v3.0.0

### ISSUE THREAD

**Issue by Neobond** [dimdenGD/OldTweetDeck#45]
Thank you for this extension. I was notified to update this morning, so I did but now I have big scrollbars on the bottom and on the right and at the top I have a notice "Page not found" but Tweetdeck is obviously working and scrolling new tweets into view.

I used to have BetterTweetDeck, but I pressed "never ask again" and I cannot get it to load anymore. I have tried disabling and enabling that extension but it won't come back.

![SNAG-0000](https://github.com/dimdenGD/OldTweetDeck/assets/42996358/7835a64b-343b-4244-87c5-0e93e0ef3fc9)

**Comment by TheClassic36** [comment]
+1 

I've found that refreshing the page a few times can get rid of the huge scroll bar & BetterTweetdeck will work again, but you will rarely get both to happen at the same time 😅

**Comment by Whirblewind** [comment]
When it was just trying to get BetterTweetdeck to stick, I would have to refresh 1-4 times. Now with this scrollbar thing trying to get both BTD and normal scrollbars can take just a handful or so many refreshes I give up. I use "Thin" scrollbars in BTD and tried to keep that set to Default to see if it would help and it didn't.

**Comment by Neobond** [comment]
This can be closed off since we now got the BTD fork working.
