### ISSUE TITLE
Link card layout is broken

### ISSUE THREAD

**Issue by haxibami** [dimdenGD/OldTweetDeck#49]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/57034105/799eb8c8-a7ac-49ae-8abd-6ca65355b3ed)

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/26517362/d94702e0-ac9d-4a86-81f8-1c3ca0845e2a)
can't reproduce, they look fine for me

**Comment by haxibami** [comment]
Sorry, it works fine for me now.

![image](https://github.com/dimdenGD/OldTweetDeck/assets/57034105/6e8dc9fc-2bfe-47f5-a7d3-7e09489968e9)

**Comment by RdNetwork** [comment]
I have the exact same issue, using OldTweetdeck and BetterTweetdeck's last versions., on Firefox Developer 117.

Usually, refreshing the page helps fixing it, but it comes back some time after that.

![image](https://github.com/dimdenGD/OldTweetDeck/assets/4118704/021e41b8-719c-4449-8f06-5ce5afd68545)

![image](https://github.com/dimdenGD/OldTweetDeck/assets/4118704/8e430fd1-3d96-404e-8950-33b65c78a044)

Layout remains broken when clicking on a tweet with a card link.
Console doesn't display anything different (that I can spot, at least) when layout is broken compared to when it's working fine.
