### ISSUE TITLE
request about Search enhance 

### ISSUE THREAD

**Issue by HanSHANGOM** [dimdenGD/OldTweetDeck#52]
In the old api, there was a way that the search results did not include handles, user names, and handles attached to mentions. That was when I put an ID that doesn't exist like @oi4h23j4kkj with OR. For example, [search word] or @[non-existent handle]
But that doesn't work now. When applying this search method, is it possible to improve in the direction of the effect presented above?
I'm using the 3.0.0 version.

Thank you for creating the oldTweetDeck.

**Comment by dimdenGD** [comment]
OTD just forwards requests to new API, I can't do anything about the fact that it behaves a little different now.
