### ISSUE TITLE
columns working again  

### ISSUE THREAD

**Issue by ItsBluey** [dimdenGD/OldTweetDeck#54]
i download v3.0.2 since i was on v3 but seems like columns are not working because it was showing me them on v3 after i updated it not anymore and if i go back to v3 they still dont show (could be a bug on my end idk) 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/ee41f17a-f1b1-4cac-8374-6af94eab5996)

**Comment by dimdenGD** [comment]
you have too many columns and are hitting rate limit

**Comment by ItsBluey** [comment]
no if i was rate limited i get notification i have never been rate limited either

**Comment by ricky-wong** [comment]
Inspect the network requests and they will probably say 429

**Comment by ItsBluey** [comment]
> 
i have no idea never inspect element for anything 
![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/3d339685-d36c-4967-b266-f4bae7613b15)

**Comment by ItsBluey** [comment]
also remove those columns to test your theory  @dimdenGD  not rate limited they are broken i cannot even add new columns

**Comment by dimdenGD** [comment]
open Console tab and screenshot errors

**Comment by ItsBluey** [comment]
> open Console tab and screenshot errors

![image](https://github.com/dimdenGD/OldTweetDeck/assets/20117258/0349a45a-be5b-4c73-9b6a-221ce3695f68)

**Comment by dimdenGD** [comment]
As some person above said I see 429 errors, which mean rate limited

**Comment by ItsBluey** [comment]
> As some person above said I see 429 errors, which mean rate limited

i am still seeing new tweets and normal tweetdeck/twitter website works just fine. lol

**Comment by ItsBluey** [comment]
okay yeah i guess i am rate limited but only tweetdeck on that account because  i can see tweets etc just fine on phone app/website but i went an alt account and tweetdeck works fine all columns work

**Comment by ItsBluey** [comment]
okay seems to be working now on both accounts so weird thanks for the info :)
