### ISSUE TITLE
Search and User Columns not loading again

### ISSUE THREAD

**Issue by cpwada** [dimdenGD/OldTweetDeck#56]
This issue appears to be back again.   I am on Version 3.0.2 Loading loop messages only on search columns. Other columns like List and Follows still work.

**Comment by dimdenGD** [comment]
F12 > Console, screenshot errors

**Comment by cpwada** [comment]
![Screenshot 2023-08-25 095523-1](https://github.com/dimdenGD/OldTweetDeck/assets/143190994/e97f0742-1708-4ab9-84fe-ffcbeabadf3c)

![Screenshot 2023-08-25 095604-2](https://github.com/dimdenGD/OldTweetDeck/assets/143190994/31428ed3-d748-4e7c-a2f3-d05766daea7d)

**Comment by dimdenGD** [comment]
These are rate limit errors, have less columns open or don't use normal Twitter since they use same endpoints
