### ISSUE TITLE
Is it problematic that `tweetdeck.dimden.dev` is present in request headers?

### ISSUE THREAD

**Issue by ricky-wong** [dimdenGD/OldTweetDeck#6]
Thanks for providing this!

Just inspected some network requests to `api.twitter.com` to see if there was anything they could catch on to. I see the request headers have `Referer: https://tweetdeck.dimden.dev` and even the response headers include `Access-Control-Allow-Origin: https://tweetdeck.dimden.dev`.

Are we concerned at all about this field? Is there a way to game the extension so that Chrome doesn't send this request header (or sends a different value) along with its API requests?

**Comment by dimdenGD** [comment]
Made it remove the header

**Comment by ricky-wong** [comment]
Verified, thank you!
