### ISSUE TITLE
The contents of the list are no longer refreshed in real time, and most lists always appear to be loading

### ISSUE THREAD

**Issue by jessechen867** [dimdenGD/OldTweetDeck#66]
The contents of the list are no longer refreshed in real time, and most lists always appear to be loading

**Comment by fabien-kerinec** [comment]
same issue here, with custom column (infinite load, but this is not exaclty an infinite load)

- specific word search
- search by @ 
- column for specific people

The columns seems to be `loading` even when response is an error

but in the network tabs i've this error 
`{"errors":[{"code":88,"message":"Rate limit exceeded."}]}` 
So i don't think this error can really be fixed

**Comment by RH-2010** [comment]
Same here also, takes up to 7 minutes before new tweets are shown, multiple tweets from one user then appear all at once.

**Comment by BopLouie** [comment]
Same problem, similar to earlier issue with all the columns stuck to "loading".

**Comment by johanhagerstrom** [comment]
I have the same issue with "specific word search"," search by @" and "column for specific people"
But just now and then. Some columns have been "loading"  all morning, and suddenly everything is fine again.

**Comment by Dajova** [comment]
That just sounds like the normal content limit. regardless of how much the old tweetdeck is back, the restriction are still there (i think its 400 tweets for new unverified and 800 for normal unverified, per day).

**Comment by fabien-kerinec** [comment]
> That just sounds like the normal content limit. regardless of how much the old tweetdeck is back, the restriction are still there (i think its 400 tweets for new unverified and 800 for normal unverified, per day).

It clearly is a normal limit and can't do anything about it because it still based on Twitter/ X API limitation

**Comment by TheAGames10** [comment]
> You can paste `localStorage.abuseAPIkeys = '1'` into Console and refresh to double your rate limit


It worked for like one column, but the rest do not load still.

I honestly do not want to wait for the rate limit exceeded thing to end. I am not a patient person, and there is like no one on Threads or BlueSky for me to keep them opened in a new tab nowadays.
