### ISSUE TITLE
Pinned tweets are not visible in users columns

### ISSUE THREAD

**Issue by Akiwave** [dimdenGD/OldTweetDeck#67]

**Comment by dimdenGD** [comment]
What

**Comment by Akiwave** [comment]
Tweets that are pinned are not visible in "User" column. Example: add @kosekibijou. [This tweet from 14h ago ](https://twitter.com/kosekibijou/status/1695986145409327481) is not visible in tweetdeck.

**Comment by dimdenGD** [comment]
I don't think they're supposed to be visible, I haven't seen them when using tweetdeck

**Comment by Akiwave** [comment]
Maybe people you follow don't use pinned tweets as much? I'm pretty sure that I had seen them regularly before the paywall. I still see them now in the "Home" column. 
I suppose this is not fixable?

**Comment by dimdenGD** [comment]
Fixed, but they'll only show if they were loaded on first page, can't show them if they're too low in the list
