### ISSUE TITLE
Issue with bulk adding to lists- leaves out half the users.

### ISSUE THREAD

**Issue by katelynjean123** [dimdenGD/OldTweetDeck#71]
The bulk-add users to lists function leaves out half the names I put in usually and can only handle a few names at a time. I usually have to add 30 and then come back like 10 minutes later to add more. It also caps users you can add ~ 150 which was something the old tweetdeck also did but for this extension even if I try adding on a different list with a different account it still will return an error message, even though it's not the same account, which before I was capped at 150 per account. Would love a fix for this!

**Comment by dimdenGD** [comment]
I tried to bulk-add 20 people and all of them got added fine, it all relies on Twitter's API and there's nothing to be done if there's a bug with their API
I didn't really understand what do you mean with second issue about 150 cap

**Comment by katelynjean123** [comment]
Yeah it works fine for like the first 30 users then starts bugging :( 150 cap = stops adding people after 150 users. That is Twitter's api though just the issue with this is if I try to switch accounts it still won't let me add.

**Comment by italomartinns** [comment]
This problem was happening since before Twitter acquisition
