### ISSUE TITLE
Cannot retrieve favorite status **PLEASE FIX ASAP**

### ISSUE THREAD

**Issue by PythonGGs** [dimdenGD/OldTweetDeck#79]
the old tweet has bug when I try to like tweets on my alt accounts it says  Cannot retrieve favorite status
![old tweeet derck bug](https://github.com/dimdenGD/OldTweetDeck/assets/88223007/3370ea5b-cb33-4da8-8e39-2ee249cf663b)
I have provided a picture

**Comment by dimdenGD** [comment]
Fixed
