### ISSUE TITLE
Won't load for Google Chrome

### ISSUE THREAD

**Issue by Fapo39** [dimdenGD/OldTweetDeck#8]
infinite loading for Google Chrome, beta/legacy doesn't even show up in cookie, works just fine on Edge but I am malding without my other firefox/chrome extensions, for the love of god make this work on mozilla firefox please

**Comment by TheAGames10** [comment]
If the person behind the extension is still here, I am not able to use the extension anymore on Chrome, as an error comes up in the extension section of Chrome:

'Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.'

I cannot even get into TweetDeck anymore even with the extension active as it takes me to Twitter to try and get me to buy tweetdeck. I really want to have TweetDeck again. :(

**Comment by dimdenGD** [comment]
That error is useless warning, extension continues to work even with that error shown

**Comment by TheAGames10** [comment]
Well, I can't get into TweetDeck anymore with the extension enabled, since it just takes me back to Twitter, wanting me to buy premium. Something definitely happened over the last hour with the extension.

**Comment by dimdenGD** [comment]
Someone reported that clearing cache worked for them, try that

**Comment by TheAGames10** [comment]
I already tried just now, but it didn't work.

Before it forced me out of TweetDeck, a pop-up kept showing up, telling me to update/re-install the extension, I did that and that's when it started forcing me out of TweetDeck.

**Comment by dimdenGD** [comment]
Did some updates, reinstall and check if it works now

**Comment by TheAGames10** [comment]
It works for the most part, tho I am seeing some display problems: (And the Direct Messages are glitched out, showing only one of my many DM chats.)

![Capture](https://github.com/dimdenGD/OldTweetDeck/assets/111199398/a18f7896-2435-4382-bf2f-3df65a048a51)

**Comment by Fapo39** [comment]
yes completely deleting all cookies/cache & re installing chrome fixed it for me too on fresh install
