### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by tanzaa3** [dimdenGD/OldTweetDeck#80]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/144087631/f4bf3391-4b03-4c15-af64-dfddc9c3b651)

3.0.6
Worked fine for more than a week, also tried install on chrome, gave same result
Have to downgrade to 1.0.2

**Comment by SilentPrayeCG** [comment]
Having same issue - infinity loading circle. Tried to clear cookies - no use.
Yesterday everything was fine (as fine as twitter can be nowadays)

**Comment by tanzaa3** [comment]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/144087631/e9713a12-4aa4-4d68-b073-b6bf8c680e95)

Seems like it might be because an issue with Github API
Maybe that's why all the code aren't loaded

**Comment by haxibami** [comment]
Tips: Set `localStorage.OTDalwaysUseLocalFiles = '1'` in browser console

**Comment by tanzaa3** [comment]
Seems to be working now
