### ISSUE TITLE
follow from accounts doesn't work

### ISSUE THREAD

**Issue by grafixel** [dimdenGD/OldTweetDeck#83]
follow from accoubts doesn't work: popup is opened and the list of accounts is shown, but nothing can be selected

browser: Chrome

**Comment by Vitoire** [comment]
I would like to bump this up and add a visual representation of the issue.
![image](https://github.com/dimdenGD/OldTweetDeck/assets/49831104/8e6ad15d-d9dc-43ec-9831-f1362b6ceaa8)
This is what it looks like. It was fixed temporarily when the new version was uploaded, but when the changes to the package were made 8 hours ago, it seems to have reverted the fix. 
Somewhat inconvenient and would appreciate a fix whenever possible!

**Comment by dimdenGD** [comment]
I didn't change anything in code related to following, also I don't see anything on your screenshot

**Comment by Vitoire** [comment]
That is exactly the issue! It should have a button that allows you to follow the account, which, as you can see (or not see) is missing. This is in Opera, Chrome seems to be working just fine
![image](https://github.com/dimdenGD/OldTweetDeck/assets/49831104/01753dd7-e234-49d4-92d6-706c07e3216e)
This is what it *should* look like when the button is actually there
