### ISSUE TITLE
Strange captcha on Tweetdeck 

### ISSUE THREAD

**Issue by vitumen** [dimdenGD/OldTweetDeck#84]
Suddenly, instead of Tweetdeck, i got redirected to anti-bot captcha with 20 (yes, 20!) steps but i got it wrong every single time, doesn't matter if i solved it correctly or not. I didn't tweeted a lot in the last hours, so i guess it wasn't something i've made. Strangely, it happened after i had changed my display name (not my @) on X.com and then refreshed the Tweetdeck tab.

EDIT: I've changed the title because i managed to pass the captcha, but still, it seemed like an odd behavior

**Comment by dimdenGD** [comment]
It's not related to extension, it's a known thing that happens when you change your name on Twitter
