### ISSUE TITLE
[Feature Request] Read longer tweets on tweetdeck

### ISSUE THREAD

**Issue by MichalisSak** [dimdenGD/OldTweetDeck#85]
Is it possible to read longer tweets on tweetdeck?
Right now it opens those links on twitter.
One-click expansion in the feed would be ideal, but isolation of a full expanded tweet like when you click on every tweet would be fine.

**Comment by Rooooooobert** [comment]
I support this request, please, if you can ;-)
Also for polls, btw.

**Comment by PresumablyPaul** [comment]
Tweets exceeding 280 characters don't display in full in feed & search columns but, I noticed over the last couple/few days that they are now displaying in full when you are viewing a user's profile within Tweetdeck.
![image](https://github.com/dimdenGD/OldTweetDeck/assets/143474048/056266c0-d417-4909-b72a-657d68f5241b)

**Comment by dimdenGD** [comment]
Because User and Search columns are now using new APIs that actually return this data, other columns still use old APIs and don't get this data

**Comment by Invicta76** [comment]
Same issue here, the "Show more" text is gone from tweets.

**Comment by dimdenGD** [comment]
API just stopped showing these, I'll see what can be done

**Comment by dimdenGD** [comment]
I've added "Expand tweet" button that will fetch full text and add it to tweet
