### ISSUE TITLE
Old Tweetdeck stopped working

### ISSUE THREAD

**Issue by erbkaiser** [dimdenGD/OldTweetDeck#86]
Some time before one hour from this post, Old Tweetdeck stopped working. Twitter now redirects to the Blue signup again.

I have version 3.0.7 of Old Tweetdeck installed.

**Comment by boilinabag** [comment]
same here. I uninstalled v3 and reinstalled it, and it came back with that blue circle redirect. seems ok for now.

**Comment by oliverschloebe** [comment]
Not working for me either.

> Something went wrong, but don’t fret — let’s give it another shot.

**Comment by erbkaiser** [comment]
I had installed the Chrome version via the release tab, I now replaced it with the direct code .zip instead and that seems to be working again, despite also saying it's 3.0.7

**Comment by oliverschloebe** [comment]
> I had installed the Chrome version via the release page, I now replaced it with the direct code .zip instead and that seems to be working again, despite also saying it's 3.0.7

Worked for me too, thanks!
