### ISSUE TITLE
No Ctrl-V paste for pictures

### ISSUE THREAD

**Issue by BKeyport** [dimdenGD/OldTweetDeck#87]
Missing feature - Ctrl-V/Command-V does not paste when it's a picture - is this able to be fixed? Seems to affect BTD pasting gifs as well. 

Thanks!

**Comment by webdados** [comment]
I was just going to open this same issue 👍

**Comment by dimdenGD** [comment]
I can paste images fine with BetterTweetDeck, if it doesn't work for you with BetterTweetDeck you should open issue in according repository, OldTweetDeck's purpose is only returning old TweetDeck but not enhancing it.

**Comment by BKeyport** [comment]
You misunderstood. I was using BTD's failing GIF paste as an example. This is happening in base Old Tweekdeck. I have no picture paste in any version of Old Tweedeck, with or without BTD. 

Please reopen and look into this.

**Comment by dimdenGD** [comment]
Tweetdeck doesn't have support for pasting images, reopen but in BetterTD repository

**Comment by BKeyport** [comment]
The original tweetdeck did.

**Comment by dimdenGD** [comment]
I don't think it could, see https://github.com/eramdam/BetterTweetDeck/issues/55
