### ISSUE TITLE
Container on tweet composer seems broken

### ISSUE THREAD

**Issue by dsomers16** [dimdenGD/OldTweetDeck#92]
Container won't close/seems to be broken to send tweets. 
![Screen Shot 2023-09-12 at 8 37 54 PM](https://github.com/dimdenGD/OldTweetDeck/assets/17286249/c41224c0-28ff-47d5-ac29-3745759abe98)

**Comment by dimdenGD** [comment]
Update to latest version (released today), and tell if it fixes this

**Comment by dsomers16** [comment]
Beautiful. Thank you so much!
