### ISSUE TITLE
Tweetdeck will no longer opening ( Version 3.0.8 )

### ISSUE THREAD

**Issue by NotScooty** [dimdenGD/OldTweetDeck#94]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/142687141/cac5a6e6-3ba6-421a-962e-0d3e94eba403)

This is all I see when I try to open tweetdeck, it worked perfectly fine last night and now I open to only this. Reinstalled the entire thing on chrome but it's not coming back.

**Comment by Kyure-A** [comment]
me too

**Comment by Kyure-A** [comment]
"Found. Redirecting to https://twitter.com/i/premium_sign_up" is now displayed when attempting to log in.

![スクリーンショット 2023-09-14 021730](https://github.com/dimdenGD/OldTweetDeck/assets/49436968/7cffde86-38a1-4251-a216-62ba49cbc651)

**Comment by TheAGames10** [comment]
This is sad, hoping for it to be fixed. :(

**Comment by dleake14** [comment]
Can't confirm similar issue. Was working as of 2 hours ago

**Comment by whimsicaliber** [comment]
> Can't confirm similar issue. Was working as of 2 hours ago

Consider checking again, same issue on my end and seems to have stopped not much more than half an hour ago.

**Comment by petrusco2** [comment]
Same issue here since like 30m

**Comment by d4r4ki4n** [comment]
confirming issue. on latest build of oldtweetdeck the redirect goes through and takes me to the subscription popup. seems like they're actively trying to shut it down now.

**Comment by archeruwu** [comment]
Twitter killed all old versions of the API, meaning OldTweetDeck is dead at the moment, and will no longer allow multi account posting anymore once it's fixed.

**Comment by BKeyport** [comment]
Oof. Feed Frozen, then same issue.

**Comment by dimdenGD** [comment]
Yes it would

**Comment by Rooooooobert** [comment]
I have just donated 50,- EUR via Paypal to keep you motivated ;-) Thanks so much for OldTweetdeck!

**Comment by archeruwu** [comment]
ITS WORKING AGAIN

**Comment by Parrelo** [comment]
> ITS WORKING AGAIN

Yessss!! Great! Thanks!!!!

**Comment by Rooooooobert** [comment]
Dimden, youre a magician, that was quick!

**Comment by d4r4ki4n** [comment]
it's uh... still not working for me

**Comment by Parrelo** [comment]
Oh...stopped working again....

**Comment by snowbound** [comment]
Same here no longer working

**Comment by Parrelo** [comment]
Not working yet for me :(

**Comment by katebevan** [comment]
Just stopped working for me too. Gah. I have been so grateful for this. Hope you can get it working again - thank you for your work on this!

**Comment by Rooooooobert** [comment]
It's back again, but I can only read all columns, but not tweet or reply ...
![Bildschirmfoto 2023-09-13 um 22 50 03](https://github.com/dimdenGD/OldTweetDeck/assets/56634383/de13c384-09b5-4c62-b1e2-f735e7811317)

**Comment by emmanu888** [comment]
Updated to the new version and i think retweets are broken? I can't retweet anything anymore.

**Comment by Rakkzi** [comment]
Stopped working for me today as well. Shame..

**Comment by Parrelo** [comment]
I installed the 3.1.0 version. Now I can see all the tweets running. However, I can do nothing (I can't tweet, retweet, etc).

**Comment by BKeyport** [comment]
Yeah. Same as Parrelo. I'm okay with this for now. Perhaps they added Premium checks to actions.

**Comment by boilinabag** [comment]
working for me. just reloaded, v3.7. thank you gods of tw.

**Comment by boilinabag** [comment]
i also cleared the cache and cleaned chrome of all cookies and stuff.

**Comment by boilinabag** [comment]
i see i cant tweet from tw. just use the desktop version.

**Comment by TheAaronLad** [comment]
on top of everything mentioned I can't view replies to tweets.

**Comment by katebevan** [comment]
I can't view replies to tweets either

**Comment by Parrelo** [comment]
Now, this is what happens
![Captura de ecrã 2023-09-13 231149](https://github.com/dimdenGD/OldTweetDeck/assets/144944965/53509fea-70a1-4afd-9087-8c6f4833b5be)

**Comment by dimdenGD** [comment]
Update to 3.1.1

**Comment by Parrelo** [comment]
Great. It working now. You're the best. Thanks!!!!!

**Comment by BKeyport** [comment]
Confirmed. Thanks, even works well with BTD.

**Comment by Parrelo** [comment]
Not working again. Sorry to send this messages but is just to inform you (I am recognized by your hard work, of course)

**Comment by nnrajui** [comment]
I'm sad it's not working, hope it gets fixed.

**Comment by BKeyport** [comment]
It works fine for me - I suspect it's because I'm lazy and went from 3.0.2 straight to 3.1.1 

Would try reinstalling.

**Comment by VelvetShadows** [comment]
Works perfectly fine for me, and I updated every step of the way. Could be A/B testing on Twitter's side that's breaking it for some people but not others, but I'd try deleting any trace of prior versions, deleting Twitter cookies and starting fresh with the latest version.

**Comment by Parrelo** [comment]
It works fine for me too. The only thing I noticed is the fact that in the feed the tts stop running for almost a minute and after that is updated and restart this cycle (stop, jump, stop, jump). But I really don't know if this "bug" is caused by my machine....
