### ISSUE TITLE
Search Columns won't load due to assignment to const variable

### ISSUE THREAD

**Issue by WizardCM** [dimdenGD/OldTweetDeck#95]
![image](https://github.com/dimdenGD/OldTweetDeck/assets/941350/9dd7183c-f8eb-4634-8627-e60bb98f2e4d)

https://github.com/dimdenGD/OldTweetDeck/blob/9221efdcf6281194e43919faf97fb0b2126b2ca2/src/interception.js#L316

```
VM50:318  TypeError: Assignment to constant variable.
    at Object.afterRequest (<anonymous>:316:22)
    at Object.interceptResponseText (<anonymous>:561:42)
    at Object.get (<anonymous>:543:52)
    at XMLHttpRequest.<anonymous> (<anonymous>:2796:197)
```

If I initialise `var data;` and enable `OTDalwaysUseLocalFiles` the issue goes away.

* Originally I thought this was #34 but the solution ended up being different.

**Comment by snowbound** [comment]
I am on 3.1.4 and Search columns when loading Tweetdeck for the first time for the day, doesn't load 2 search columns 3 hours later still spinning circles.
