### ISSUE TITLE
Activity column not working

### ISSUE THREAD

**Issue by caiosacramento** [dimdenGD/OldTweetDeck#97]
in  lattest version [3.1.1], activity column feature is not working

![image](https://github.com/dimdenGD/OldTweetDeck/assets/9254547/a73f5c55-dfeb-414e-a227-a42c322c6a31)

**Comment by dimdenGD** [comment]
It will most likely never be fixed

**Comment by caiosacramento** [comment]
what problem are you having, twitter broken the way for take data?

**Comment by SilentPrayeCG** [comment]
Well, updated tweetdeck didn't even had "activity tab", I thought they gonna implement in future, but time passed, they killed old tweetdeck, made new tweetdeck pay only, and even for money you still don't have activity tab... it's pathetic.
I assume they removed mechanism that acquired that data from their API or something?
